### ISSUE TITLE
window-1.2.0+1 全屏字体自动加粗

### ISSUE THREAD

**Issue by qweqw123** [liuchuancong/pure_live#1]
window-1.2.0+1 非全屏时没问题,只要一全屏就自动加粗字体

**Comment by liuchuancong** [comment]
截个屏看看

**Comment by qweqw123** [comment]
之前反馈后换回原版了,今天才看到邮件
[image: image.png]
这个是没全屏的弹幕字体
[image: image.png]
这个全屏后弹幕字体自动缩小后加粗了,最大就这么大了

bobobo ***@***.***> 于2023年9月18日周一 14:46写道：
