### ISSUE TITLE
同步系统音量

### ISSUE THREAD

**Issue by Noooo9** [liuchuancong/pure_live#102]
2个方面的需求，希望作者考虑。
1、win版和安卓版调节音量会同步调节系统音量的，希望分开，不要改动系统音量，特别是PC端。
2、还有安卓端的屏幕方向是默认跟随系统设置的，无法设置更改。由于我个人平常不习惯打开自动旋转，但是看视频手机可能会左横放或右横放，希望可以加个开关设置屏幕方向可选择跟随系统，或跟随传感器或锁定竖向横向之类。
辛苦了～

**Comment by liuchuancong** [comment]
想偷懒 不想搞 嘿嘿
