### ISSUE TITLE
哔哩直播 娱乐和聊天室分区无法读取播放地址

### ISSUE THREAD

**Issue by sanfutian2** [liuchuancong/pure_live#105]
安卓1.56最新版本哔哩直播无法读取娱乐和聊天室分区直播地址，弹幕显示正常 1.55也不行

**Comment by liuchuancong** [comment]
@sanfutian2 bilibili 内部限制了 拿到的链接放到浏览器都会显示已过期，直播不会，应该是使用了直播sdk的限制，而不是推流
