### ISSUE TITLE
虎牙直播播放几秒后会自动暂停

### ISSUE THREAD

**Issue by FadeJay** [liuchuancong/pure_live#106]
虎牙直播播放几秒后会自动暂停

**Comment by psy2024** [comment]
确实，从前两天开始，PC端出现了这个问题，几秒后就看不了了，手机上可以看，不知道为什么

**Comment by liuchuancong** [comment]
@psy2024 @twodoging @FadeJay  是电脑吗

**Comment by liuchuancong** [comment]
估计是部分限制了 我抓包看下吧

**Comment by FadeJay** [comment]
> @psy2024 @twodoging @FadeJay 是电脑吗

对的，电脑端有这个问题，手机端我试了下没问题

**Comment by liuchuancong** [comment]
还是有问题  直播没有问题 看一些电影或者视频轮播有问题

**Comment by liuchuancong** [comment]
目前貌似是登陆的问题 官网也是会暂停然后让登陆

**Comment by liuchuancong** [comment]
设置-使用mpv播放器
