### ISSUE TITLE
部分直播会提示无法获取地址

### ISSUE THREAD

**Issue by jlu511** [liuchuancong/pure_live#108]
![image](https://github.com/liuchuancong/pure_live/assets/64378673/2f293fa0-e26e-4762-a707-61753ae41082)
r如图，bili直播

**Comment by jlu511** [comment]
![image](https://github.com/liuchuancong/pure_live/assets/64378673/2f3e4992-709e-4458-8cdf-25b1703613bf)
网易cc里面基本打不开，显示  无法读取播放清晰度

**Comment by liuchuancong** [comment]
#106

**Comment by liuchuancong** [comment]
无法读取播放清晰度 代表获取不到直播间的直播路线
