### ISSUE TITLE
界面滑动刷新率只有60hz

### ISSUE THREAD

**Issue by whalexz** [liuchuancong/pure_live#109]
设备是小米13，在系统设置里调不了刷新率，界面滑动只有60hz，看起来不太流畅
![Screenshot_2024-02-26-17-04-32-256_com mystyle pu](https://github.com/liuchuancong/pure_live/assets/39986046/e65480c0-01f5-4035-881c-4ef9bf3a59c2)
![Screenshot_2024-02-26-17-05-50-321_com xiaomi mis](https://github.com/liuchuancong/pure_live/assets/39986046/efa15ea0-75bb-457e-a4f7-287e3260bfb6)

**Comment by liuchuancong** [comment]
刚开始比较卡 因为加载的平台过多 尝试设置-》平台设置
