### ISSUE TITLE
純粹直播 1.5.7版，看虎牙直播會自動在十分鐘處而不能看了

### ISSUE THREAD

**Issue by chenhy22tw** [liuchuancong/pure_live#111]
純粹直播 1.5.7版，看虎牙直播會自動在十分鐘處而不能看了，請修正，謝謝

**Comment by chenhy22tw** [comment]
停在十分鐘處

**Comment by chenhy22tw** [comment]
HuYa(虎牙直播第三方TV版) v2.1.0 直播_弹幕_一起看 支持抖音直播，此軟件沒這個問題

**Comment by chenhy22tw** [comment]
阿斗归来了也是停在三分钟处就看不了了

**Comment by liuchuancong** [comment]
#106

**Comment by chenhy22tw** [comment]
我试过安卓手机和电视盒都是一样，三分钟就停了不能看了

**Comment by chenhy22tw** [comment]
估計是虎牙做了什麼限制

**Comment by liuchuancong** [comment]
@chenhy22tw 网页版也是

**Comment by chenhy22tw** [comment]
剛看了一下，阿斗歸來了 結果是在五分鐘處停了就不能看了

**Comment by chenhy22tw** [comment]
好像又有點random 才停

**Comment by chenhy22tw** [comment]
我打開網頁版可以正常觀看

**Comment by chenhy22tw** [comment]
可是我用，1.5.7 版在我的電視盒上看不到兩分鐘就停住不動了

**Comment by chenhy22tw** [comment]
我是看，阿斗歸來了，會這樣，止戈電影又好像可以看

**Comment by chenhy22tw** [comment]
科幻夢工廠，看了兩分鐘後停住了不能看了

**Comment by chenhy22tw** [comment]
刷新之後依然是黑屏

**Comment by chenhy22tw** [comment]
阿斗歸來了，看了兩分鐘又卡住了，真奇怪，彈幕還有在跑

**Comment by liuchuancong** [comment]
@chenhy22tw 目前测试是直播源限制了  因为正常的直播是可以观看的 但是类似于视频轮播增加了限制 可能是登录 可能是其他 我去隔壁项目试试能不能一直观看吧

**Comment by chenhy22tw** [comment]
好的，謝謝你，辛苦了，希望能儘快破解虎牙的限制

**Comment by liuchuancong** [comment]
@chenhy22tw  https://github.com/xiaoyaocz/dart_simple_live  去这里提问试试  我大部分代码也是抄他的 毕竟都是一样的App，代码也都类似，我目前也没有好办法。

**Comment by chenhy22tw** [comment]
我試了好幾次，用1.4.9 版在我的安卓手機和電視盒上只能看兩分鐘就自動黑屏不能看了，可是我用另外一個網站下載的app, HuYa-2.1.0-20240223.apk 裡的娱乐天地里的一起看里的虎牙，看阿斗归来了人家是正常的，给你参考。下载地址我是 https://www.fenxm.com/1027.html

**Comment by chenhy22tw** [comment]
里面还有四线路，默认的阿里的线路是可正常绝望观看阿斗归来了的

**Comment by chenhy22tw** [comment]
观看

**Comment by chenhy22tw** [comment]
里面还有四线路，默认的阿里的线路是可正常观看阿斗归来了的

**Comment by liuchuancong** [comment]
@chenhy22tw 不开源  无法获取具体逻辑

**Comment by chenhy22tw** [comment]
喔

**Comment by chenhy22tw** [comment]
请参请考他的，源代码 https://github.com/jayjd/huyatv/releases/tag/2.1.0

**Comment by chenhy22tw** [comment]
试过四条线路，发现腾讯的线路观看最稳定

**Comment by chenhy22tw** [comment]
https://github.com/jayjd/HuYaTv/issues/21

**Comment by liuchuancong** [comment]
@chenhy22tw 使用mpv播放试试

**Comment by chenhy22tw** [comment]
請問是哪個 mpv 呢？

**Comment by chenhy22tw** [comment]
只能用虎牙直播官方版來看阿斗歸來了

**Comment by liuchuancong** [comment]
@chenhy22tw  设置  切换播放器

**Comment by chenhy22tw** [comment]
嗯，可以看了

**Comment by chenhy22tw** [comment]
謝謝
