### ISSUE TITLE
弹幕合并和界面滑动灵敏度等问题和建议                                                                                                     

### ISSUE THREAD

**Issue by recycle007** [liuchuancong/pure_live#112]
1，我以为弹幕合并是合并重复弹幕的意思，但即便设置0也默认合并了重复弹幕
2，界面滑动灵敏度过于灵敏了，划后台或者下拉状态栏经常直接把声音拉满，很难控制合适的音量或者亮度
3，在出现网络波动时会出现画面卡住不自动刷新或者等好几秒才刷新的情况
4，希望能在全屏界面加入直接进入其他关注直播间的功能

**Comment by liuchuancong** [comment]
弹幕合并是相似度 合并 比如一句话和另外一句话相似程度  界面滑动 与操作有关 其他功能因为架构的关系 无法支持，需要大改，例如 现在打开直播间 为了优化 进入直播间打开播放器 而加入其他直播间 就要将 播放器打开就初始化  添加直播间时类似于歌曲。
