### ISSUE TITLE
1.5.8 版測試報告

### ISSUE THREAD

**Issue by chenhy22tw** [liuchuancong/pure_live#114]
大哥，我安裝了1.5.8 版看了兩個多小時的，阿斗歸來了，後又自動停住了，關掉再開後試了兩次都是在播放2到3分鐘後會自動停住，現在我切換播放器成mpv 播放器，暫時沒有停住的現像發生，現在繼續測試中，跟您報告一下，謝謝。

**Comment by chenhy22tw** [comment]
剛剛切換回 EXO 播放器播放了三分鐘有自動停住了

**Comment by chenhy22tw** [comment]
我测试的是 1.5.8-安卓_手机低版本或电视.apk

**Comment by liuchuancong** [comment]
@chenhy22tw 目前无法定位 源的问题  使用exo 播放器线路四试试 但是用exo看其他直播没有这个问题，最好还是使用mpv播放器好一点

**Comment by chenhy22tw** [comment]
看來虎牙真的是鐵了心，極力控制他的直播，讓人不能輕易地看啊

**Comment by chenhy22tw** [comment]
連虎牙直播自己的軟件都會有看了一段時間之後就會自動停住，然後又重新回到搜索的畫面，虎牙真是沒救了

**Comment by liuchuancong** [comment]
部分直播间会这样

**Comment by chenhy66tw** [comment]
大哥,
虎牙-止戈电影,https://live.metshop.top/huya/19863777
虎牙-阿斗歸來了,https://live.metshop.top/huya/13303478
我試了一下, 可以用pot player 播放, 給您參考

**Comment by liuchuancong** [comment]
https://live.metshop.top/huya/13303478  这个链接是第三方的 不是虎牙官方的，我是实时抓去huya的网页获取的直播源

**Comment by liuchuancong** [comment]
@chenhy66tw 不如做成M3u 直接在网络板块播放

**Comment by liuchuancong** [comment]
```https://www.123pan.com/s/Jucxjv-NwYYd.html```  有个huya.m3u 你在设置中导入就可以了，在网络模块导入

**Comment by liuchuancong** [comment]
先打开APP 然后将文件  直接用App打开会自动导入

**Comment by chenhy22tw** [comment]
https://github.com/jayjd/huyatv/releases/tag/2.1.1

**Comment by liuchuancong** [comment]
@chenhy22tw @chenhy66tw 使用线路三试试  目前可以一直播放

**Comment by chenhy22tw** [comment]
請問在哪裡選擇線路三呢？

**Comment by liuchuancong** [comment]
![image](https://github.com/liuchuancong/pure_live/assets/36957912/284fb3cd-f0aa-4a02-84b5-553f2f0e2e0e)
@chenhy22tw

**Comment by liuchuancong** [comment]
貌似偶尔可以偶尔不行

**Comment by chenhy22tw** [comment]
我這邊試了也是一樣

**Comment by liuchuancong** [comment]
@chenhy66tw  @chenhy22tw 上传了1.5.9版本 我自己看了很久没问题帮忙测一下看看有问题没

**Comment by liuchuancong** [comment]
@chenhy22tw 我看了半小时了没问题，你试下别的还有啥问题没 没有我就发版本了

**Comment by chenhy22tw** [comment]
1.5.9 版，虎牙的，科幻夢工廠，線路一，不能看，線路二可以看，如附件。

bobobo ***@***.***> 於 2024年3月5日 週二 18:34 寫道：

**Comment by liuchuancong** [comment]
@chenhy22tw 换线路就可以了 部分直播也是这样 参数不一样 直播源也不一样 也没报错

**Comment by liuchuancong** [comment]
也会自动切换线路的

**Comment by chenhy66tw** [comment]
1.5.9版，虎牙的，科幻夢工廠，線路二，會停在開始的時候，如附件

bobobo ***@***.***> 於 2024年3月5日 週二 18:44 寫道：

**Comment by chenhy22tw** [comment]
1.5.9版，虎牙的，松軒說電影，線路一，不能看，線路二，會卡住，如附件。

chenhy66tw ***@***.***> 於 2024年3月5日 週二 18:51 寫道：

**Comment by chenhy22tw** [comment]
嗯，科幻夢工廠，會自動切換到線路二的源，可以看的版本是，1.5.9-安卓_手机低版本或电视.apk，會卡住的是1.5.9-安卓_手机高版本.apk。

陳鴻昀 ***@***.***> 於 2024年3月5日 週二 19:01 寫道：

**Comment by chenhy22tw** [comment]
1.5.9版，安卓電視版可以看的，安卓手機版會卡住，僅供參考。

陳鴻昀 ***@***.***> 於 2024年3月5日 週二 19:01 寫道：
