### ISSUE TITLE
横屏画面显示不全

### ISSUE THREAD

**Issue by turtlerwong** [liuchuancong/pure_live#115]
![Screenshot_2024-03-01-13-50-29-66_b290cf9cc3b1cbf2201bfd68bd36ed45](https://github.com/liuchuancong/pure_live/assets/152056716/4b5a7d6d-b266-4f58-a5e6-eeda038956e9)
以前横屏左边是画面右边是弹幕，现在弹幕没了，画面只能显示2/3，望优化

**Comment by liuchuancong** [comment]
好的，主要是要检测设备的宽高，和设备的方向进行适配，比较乱

**Comment by liuchuancong** [comment]
1.6.0
