### ISSUE TITLE
虎牙一起看模块播放失败,疑似官方做出限制。

### ISSUE THREAD

**Issue by twodoging** [liuchuancong/pure_live#116]
有个IPTV的项目，也是遭遇到同等问题。https://github.com/youshandefeiyang/LiveRedirect/tree/main/Golang，不知是否具有参考价值。

**Comment by liuchuancong** [comment]
#114 下载m3u导入进行观看

**Comment by liuchuancong** [comment]
@twodoging 使用线路三
