### ISSUE TITLE
关于增加全屏播放视频清晰度调整按钮的建议

### ISSUE THREAD

**Issue by girlNormal** [liuchuancong/pure_live#119]
大佬，现在软件在全屏播放的时候因为网络问题可能会需要切换视频清晰度，但是操作起来很麻烦。方便的话能不能在全屏播放的界面增加一个清晰度调整的选项，这样的话直接点击就可以调整了。就不要退出去或者点几次才调整好了。
辛苦大佬了。

**Comment by liuchuancong** [comment]
网络问题点刷新就好了，软件会自动切换线路，清晰度请在设置中自行配置.
