### ISSUE TITLE
windows版本存在内存泄漏问题

### ISSUE THREAD

**Issue by xzy666666** [liuchuancong/pure_live#121]
在观看了一两个小时后，内存占用从150M慢慢涨到1G，2G，退出直播间可以释放一部分但无法完全释放，必须重新打开程序才恢复正常

**Comment by liuchuancong** [comment]
可能是播放器内存泄露，目前我看了很久，并未出现内存超过400M, 是否为必显呢

**Comment by xzy666666** [comment]
好的大佬，目前不怎么影响使用

**Comment by liuchuancong** [comment]
@twodoging  插件市场没有好的支持windows的播放器 需要作者更新

**Comment by orency** [comment]
> @twodoging 插件市场没有好的支持windows的播放器 需要作者更新

windows10以上也有自带的用于多媒体的MFT框架,类似于安卓的mediacodec,exo
或者这个封装好囊括多种解码后端的mdk
[https://github.com/wang-bin/mdk-sdk/](https://github.com/wang-bin/mdk-sdk/)
个人感觉很多方面强于Mpv,比如支持D3D12解码,
可惜就是未开源,只提供编译好的库使用

**Comment by liuchuancong** [comment]
VLC效果也不好之前用过

**Comment by wzgrx** [comment]
确实，看一段时间会卡一下，内存占用从200到1500mb

**Comment by liuchuancong** [comment]
> > @twodoging 插件市场没有好的支持windows的播放器 需要作者更新
> 
> windows10以上也有自带的用于多媒体的MFT框架,类似于安卓的mediacodec,exo 或者这个封装好囊括多种解码后端的mdk https://github.com/wang-bin/mdk-sdk/ 个人感觉很多方面强于Mpv,比如支持D3D12解码, 可惜就是未开源,只提供编译好的库使用

用的就是这个 内核就是它这个  但是还是存在内容泄露

**Comment by liuchuancong** [comment]
[https://github.com/wang-bin/mdk-sdk/issues/195](#195)
