### ISSUE TITLE
安卓14每次重启必出现奔溃情况

### ISSUE THREAD

**Issue by diave971** [liuchuancong/pure_live#122]
![Screenshot_20240323-010332](https://github.com/liuchuancong/pure_live/assets/60306114/ddd0a634-64d2-4e66-b2ee-8cef9f7eaee7)
如图

**Comment by diave971** [comment]
版本1.6.0

**Comment by liuchuancong** [comment]
@diave971 关闭后台播放 或者切换播放器 为mpv最好

**Comment by diave971** [comment]
> @diave971关闭后台播放或切换播放器为mpv最好

默认没开后台播放的，切换播放器为mpv，问题依然存在…

**Comment by liuchuancong** [comment]
手机问题 吗 ，目前不知道崩溃原因啊
