### ISSUE TITLE
希望发布iOS和mac 版本

### ISSUE THREAD

**Issue by momo1994123** [liuchuancong/pure_live#124]
对于苹果用户来说，很期待体验下

**Comment by liuchuancong** [comment]
没有苹果电脑

**Comment by momo1994123** [comment]
> 没有苹果电脑
大佬可以试试
https://zhuanlan.zhihu.com/p/628649833?utm_id=0

**Comment by momo1994123** [comment]
> 没有苹果电脑

我有苹果电脑，如果需要的话可以提供支持

**Comment by liuchuancong** [comment]
@momo1994123 需要有开发经验的才行
