### ISSUE TITLE
〔建议〕希望增加快捷手势切换关注或者最近观看

### ISSUE THREAD

**Issue by ttttechno** [liuchuancong/pure_live#126]
全屏长按屏幕调出或者左右手势调出，以为这个太方便了希望增加🙂

**Comment by liuchuancong** [comment]
@ttttechno  架构的原因不太合适，进直播间先是半屏，此时为初始播放器时间，然后是全屏切换，退出返回关注列表为销毁播放器，以此循环，优化内存。全屏切换也会是先是半屏然后是全屏，影响体验，也会偶尔导致出现两个直播间的声音。
