### ISSUE TITLE
PC端应用图标过大，特别是在WIN10上，固定到开始屏幕展示的图标感觉很别扭。

### ISSUE THREAD

**Issue by KIITTID** [liuchuancong/pure_live#129]
如图。
![0240412082522](https://github.com/liuchuancong/pure_live/assets/32213083/52019a73-2563-449c-830f-00737d80971b)

**Comment by liuchuancong** [comment]
![image](https://github.com/liuchuancong/pure_live/assets/36957912/0af664c3-1ae9-410b-8f64-5556e0fadf20)
是不是系统不兼容，这个是win11打包出来的良好。

**Comment by KIITTID** [comment]
> ![image](https://private-user-images.githubusercontent.com/36957912/321825729-0af664c3-1ae9-410b-8f64-5556e0fadf20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4ODUzNTAsIm5iZiI6MTcxMjg4NTA1MCwicGF0aCI6Ii8zNjk1NzkxMi8zMjE4MjU3MjktMGFmNjY0YzMtMWFlOS00MTBiLThmNjQtNTU1NmUwZmFkZjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAxMjQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNTRmOGYwODQ3YWFiMmMyMGIyYmZhMTA3YzRhNTAwMjFmNWZmYzAxNjU1YWNiZTFjOWQyYmVjMDc1ZGExYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sF5h2JMrQrvyL8H4N1qF0DvgiWmY4I4Vm-CTIqM6pYg) 是不是系统不兼容，这个是win11打包出来的良好。

就是系统兼容性的问题，WIN10和WIN11的开始菜单毕竟区别太大了

**Comment by liuchuancong** [comment]
@KIITTID  打开exe可执行文件的包安装试下
