### ISSUE TITLE
增加APP中打开功能

### ISSUE THREAD

**Issue by zhusuner** [liuchuancong/pure_live#135]
![Screenshot_2024_0416_112740](https://github.com/liuchuancong/pure_live/assets/80241679/231ce67d-cd1d-42ff-8dd1-1c187014f28c)
建议直接搬过来，很好用

**Comment by liuchuancong** [comment]
@zhusuner  打开什么？ 什么意思

**Comment by liuchuancong** [comment]
@twodoging @zhusuner 已经添加 没发包 自己下载吧
