### ISSUE TITLE
关注页的平台显示是不是应该与平台设置保持一致

### ISSUE THREAD

**Issue by Jacobax** [liuchuancong/pure_live#137]
或者更灵活点单独由用户自选显示哪些平台，再加一栏“全部”
![Screenshot_2024-04-16-16-52-50-711_com.mystyle.purelive.jpg](https://github.com/liuchuancong/pure_live/assets/23228895/259f2189-e844-4533-82cd-411b406d8688)

![Screenshot_2024-04-16-16-52-29-237_com.mystyle.purelive.jpg](https://github.com/liuchuancong/pure_live/assets/23228895/5a68e328-588c-4658-8776-3075ba88418f)

**Comment by liuchuancong** [comment]
@Jacobax 重新下载 已经优化了
