### ISSUE TITLE
TV版的确定键用不了

### ISSUE THREAD

**Issue by kurin8** [liuchuancong/pure_live#140]
装在TV盒子上，TV版的确定键用不了，手机版没问题

**Comment by liuchuancong** [comment]
下载TV版 使用

**Comment by liuchuancong** [comment]
手机就用不了确定键

**Comment by kurin8** [comment]
就是装的TV版，遥控器的确定键不起作用

**Comment by liuchuancong** [comment]
那没办法，盒子硬件的关系 目前不知道你的遥控器确定按键是什么

**Comment by xif12jhj** [comment]
我也是 用的是魔百盒的通用遥控器 可以使用悟空遥控的

**Comment by liuchuancong** [comment]
换个遥控器软件试试 我记得有那种手机当电视遥控器的那种  因为不同盒子确定键对应的key 值可能设置的不一样不通用 就是这样子 这种是盒子厂商特立独行
