### ISSUE TITLE
反应tv版本的 3个bug

### ISSUE THREAD

**Issue by neuopzx** [liuchuancong/pure_live#142]
1,设置里面的“首选清晰度”和“默认平台”修改后不能保存，重新进入后恢复默认。
2，数据同步功能可以下载配置，但是重新安装app后,上传配置文件，却显示失败！
3，利用搜索功能搜索“抖音”平台主播经常失效，希望增加一个利用房间号直接进入的功能。这样可以在电脑或者手机上手动找到主播的房间号，然后直接进直播间。这样就不受搜索的限制！

**Comment by fyinnn** [comment]
第三条我也想说，希望加入房号搜索

**Comment by liuchuancong** [comment]
@fyinnn  @neuopzx  都已经修复了  下载最新的就可以  手机和windows有个链接访问 搜索不到的直播间用链接访问 进行关注后刷新即可。
