### ISSUE TITLE
最新版本的tv低版本的 3个bug

### ISSUE THREAD

**Issue by neuopzx** [liuchuancong/pure_live#143]
1,设置里面的“首选清晰度”和“默认平台”这2项修改后不能保存，重新进入后恢复默认。只有这2项不正常。
2，数据同步功能可以下载配置，但是重新安装app后,上传配置文件，上传显示成功，但是app端显示配置失败！
3，利用搜索功能搜索“抖音”平台主播经常失效，希望增加一个利用房间号直接进入的功能。这样可以在电脑或者手机上手动找到主播的房间号，然后直接进直播间。这样就不受搜索的限制！

作者的123盘里面手机和电脑昨天都有了166版，只有电视还是只有165版 ，不知道是不是作者在166版本里面进行了修正。

**Comment by liuchuancong** [comment]
1.2问题以及修复下载最新的包即可，第三个问题已经在1.6.5已经添加上去了 手机右上角添加直播间关注即可
