### ISSUE TITLE
Windows 平台弹幕速度设置逻辑有误

### ISSUE THREAD

**Issue by VeleSila** [liuchuancong/pure_live#146]
按照正常理解应该是弹幕速度的数字越大弹幕漂屏速度越快,反之漂屏速度越慢.

目前的逻辑是反的.

尝试了全新安装,问题依旧.

**Comment by liuchuancong** [comment]
@VeleSila  此为一条弹幕动画的时长 并不是数字越大 越快的意思。

**Comment by VeleSila** [comment]
是我对照安卓的设置的时候没有仔细测试安卓的效果,有点想当然了.不好意思.

**Comment by VeleSila** [comment]
是我对照安卓的设置的时候没有仔细测试安卓的效果,有点想当然了.不好意思.
