### ISSUE TITLE
b站的直播有问题

### ISSUE THREAD

**Issue by MoRanHongChenLT** [liuchuancong/pure_live#150]
![image](https://github.com/liuchuancong/pure_live/assets/120862503/57e04392-7801-4833-85d5-18cc36907def)
无法读取播放地址

**Comment by liuchuancong** [comment]
语音房

**Comment by MoRanHongChenLT** [comment]
> 语音房

不是语音房啊！同样的主播我用b站是有画面的
![image](https://github.com/liuchuancong/pure_live/assets/120862503/1f69ec19-23da-4095-b8d4-0e004a084802)
![image](https://github.com/liuchuancong/pure_live/assets/120862503/9df749a4-a61e-4efd-86c3-223d7382c288)

**Comment by liuchuancong** [comment]
B站直播分两种 游戏和娱乐房 娱乐房是集成第三方SDK搞的，播放流拿到就失效了 应该有限制
