### ISSUE TITLE
直播界面增加定时关闭功能

### ISSUE THREAD

**Issue by modj254** [liuchuancong/pure_live#151]
希望在直播界面内(横屏或全屏)增加快捷定时关闭功能，而不是在设置里

**Comment by modj254** [comment]
刚刚测试了定时关闭功能，发现打开一次之后，后面每次进入app都是默认打开状态，然后到时间app就自动关闭了，这个感觉是bug吧

**Comment by liuchuancong** [comment]
@modj254 设置中关了就行

**Comment by 404-BugNotFound** [comment]
> 没必要

有必要啊大佬，晚上想听着声音睡，顺手设置个定时退出直播间是刚需啊
