### ISSUE TITLE
【已解决】【bug】关注了主播以后进入直播间但是右下角还是显示未关注

### ISSUE THREAD

**Issue by NTCYE** [liuchuancong/pure_live#152]
从关注列表进直播，右下角还是显示关注按钮，实际上已经关注。
关注了一个主播以后重新进直播间右下角还是显示未关注，但是❤️已经点亮，重进软件右下角还是显示关注按钮
![IMG_20240423_142502](https://github.com/liuchuancong/pure_live/assets/117371952/7241a7c7-b2d7-4eb1-9b7d-19841879d116)
![IMG_20240423_142513](https://github.com/liuchuancong/pure_live/assets/117371952/0aa0c94f-ed8d-43e4-9bb4-2d24f127b6c3)

**Comment by liuchuancong** [comment]
重新下载安装包

**Comment by NTCYE** [comment]
> 重新下载安装包

好的，卸载后重新下载安装了解决了👍🏻
