### ISSUE TITLE
【功能建议】优化弹幕关键词屏蔽功能和增加全屏画中画按钮

### ISSUE THREAD

**Issue by NTCYE** [liuchuancong/pure_live#153]
如题，看直播的时候一些弹幕想要屏蔽(因为总有些人变着法子刷屏)，但是每次需要退出直播间然后进左上角设置里添加关键词，这个操作逻辑感觉有点繁琐，【希望可以加到直播界面中的弹幕设置里或者其他易于点击的地方】
  第二个就是就是画中画按钮似乎只有未全屏时显示在右上角可以用，全屏就不显示不能用了，这样的话感觉这功能就少了一半的实用性，【所以希望全屏时也能将画中画按钮显示在右上角方便使用】
![IMG_20240423_143310](https://github.com/liuchuancong/pure_live/assets/117371952/c1613866-e778-4413-a25d-1a468c1714ab)
![Screenshot_2024-04-23-14-32-48-474_com mystyle purelive](https://github.com/liuchuancong/pure_live/assets/117371952/873a283b-a1b2-4536-aabe-4de20ebb7cd3)
![Screenshot_2024-04-23-14-32-44-225_com mystyle purelive](https://github.com/liuchuancong/pure_live/assets/117371952/b2b57758-86db-4857-8462-f70efef2540c)
![IMG_20240423_145730](https://github.com/liuchuancong/pure_live/assets/117371952/f8314a8b-9c7b-409e-8f6a-0950acbc40e0)

**Comment by liuchuancong** [comment]
弹幕屏蔽 是一个完整的增删显示的过程 弹窗太小 你可以添加类似于 个别字符 以及开启弹幕过滤，至于第二点画中画为exoPlayer 功能  https://developer.android.google.cn/develop/ui/views/picture-in-picture?hl=zh  都已经全屏显示了为何还要开启画中画 与逻辑不符

**Comment by NTCYE** [comment]
> 弹幕屏蔽 是一个完整的增删显示的过程 弹窗太小 你可以添加类似于 个别字符 以及开启弹幕过滤，至于第二点画中画为exoPlayer 功能 https://developer.android.google.cn/develop/ui/views/picture-in-picture?hl=zh 都已经全屏显示了为何还要开启画中画 与逻辑不符

小白没太看明白第一个回复😅。我只是觉得我这俩建议能更方便使用。
  我意思就是能不能在看直播时也可以添加关键词屏蔽，而不是只能通过退出直播间然后进设置里添加。你想想  要退出直播间去设置里添加关键词反而感觉操作逻辑有些繁琐，在看直播时直接就能添加关键词屏蔽不是更方便吗。
  关于第二点全屏下加个小窗按钮：我觉得小窗功能无论是全屏或者非全屏都是需要的，因为很多人大多数情况下应该都是全屏看直播的，当全屏观看时要切换到别的app时直接点个小窗接着看会更方便，所以全屏也更加需要一个小窗按钮。
  顺道说个【BUG】，因为3个播放器我都尝试开启或关闭硬解码看直播，后台播放时无论我使用3个播放器中的哪一个，锁屏或者切换应用或者划到后台过个几秒钟直播都会中断没声音。app省电模式白名单跟后台锁定都设置了还是没用。所以只能通过小窗模式来暂时代替后台播放了
系统是[Android11.小米10Pro.MIUI12.5.10]
app版本[1.6.8]
