### ISSUE TITLE
弹幕屏蔽 是一个完整的增删显示的过程 弹窗太小 你可以添加类似于 个别字符 以及开启弹幕过滤，至于第二点画中画为exoPlayer 功能  https://developer.android.google.cn/develop/ui/views/picture-in-picture?hl=zh  都已经全屏显示了为何还要开启画中画 与逻辑不符

### ISSUE THREAD

**Issue by NTCYE** [liuchuancong/pure_live#159]
弹幕屏蔽 是一个完整的增删显示的过程 弹窗太小 你可以添加类似于 个别字符 以及开启弹幕过滤，至于第二点画中画为exoPlayer 功能  https://developer.android.google.cn/develop/ui/views/picture-in-picture?hl=zh  都已经全屏显示了为何还要开启画中画 与逻辑不符
________________

 小白没太看明白第一个回复😅。我觉得我这俩建议能更方便使用。
  我意思就是能不能在看直播时也可以添加关键词屏蔽，而不是只能通过退出直播间然后进设置里添加。你想想  要退出直播间去设置里添加关键词反而感觉操作逻辑有些繁琐，在看直播时直接就能添加关键词屏蔽不是更方便吗。
  关于第二点全屏下加个小窗按钮：我觉得小窗功能无论是全屏或者非全屏都是需要的，因为很多人大多数情况下应该都是全屏看直播的，当全屏观看时要切换到别的app时直接点个小窗接着看会更方便，所以全屏也更加需要一个小窗按钮。
  顺道说个【BUG】，因为3个播放器我都尝试开启或关闭硬解码看直播，后台播放时无论我使用3个播放器中的哪一个，锁屏或者切换应用或者划到后台过个几秒钟直播都会中断没声音。app省电模式白名单跟后台锁定都设置了还是没用。所以只能通过小窗模式来暂时代替后台播放了
系统是[Android11.小米10Pro.MIUI12.5.10]
app版本[1.6.8]

**Comment by liuchuancong** [comment]
@NTCYE  只有exoplayer 支持后台播放 如果无法后台播放 请取消限制电量 以及省电策略  我在息屏观看一小时后仍然可以保持后台播放  设备是小米平板6 pro

**Comment by NTCYE** [comment]
6，白瞎我打这么多字，你真是一点不看啊，浪费我感情😓

**Comment by liuchuancong** [comment]
@NTCYE 凑合用着呗 给你改了别人又有问题
