### ISSUE TITLE
奇思妙想之直播多页化

### ISSUE THREAD

**Issue by twodoging** [liuchuancong/pure_live#168]
首先对看到暂停开发新功能表示理解，还是要多休息。
最近看到一个哔哩第三方客户端，其UI界面让我突发灵感。
https://github.com/ywmoyue/biliuwp-lite
直播是否也可以做成多页化设计，类似浏览器标签页效果。
<img width="1277" alt="Snipaste_2024-05-25_20-28-51" src="https://github.com/liuchuancong/pure_live/assets/114479160/2567be39-92c8-4370-b3d0-1b428acebf8a">

**Comment by liuchuancong** [comment]
会卡顿 以及占用同一声道
