### ISSUE TITLE
tv重构版本 遥控器ok键 没有作用

### ISSUE THREAD

**Issue by sleel** [liuchuancong/pure_live#169]
rt  
重构版本用的体验不错，感谢老哥辛勤开发！现在发现这个问题，重构版本遥控器ok没作用，老版本是可以用，希望老哥有时间修复一下

**Comment by liuchuancong** [comment]
@sleel  不知道啥盒子 都能用的啊

**Comment by sleel** [comment]
> @sleel 不知道啥盒子 都能用的啊

t95z  plus老外贸盒子    以前的老版本遥控器没问题

**Comment by liuchuancong** [comment]
@sleel  
![image](https://github.com/liuchuancong/pure_live/assets/36957912/d7f90a70-68b2-4af5-9737-741f23cee82c)
是zhe'z这种遥控器嘛

**Comment by sleel** [comment]
![IMG_2903](https://github.com/liuchuancong/pure_live/assets/30924409/ee101feb-c0ee-46f0-be55-d3bf33bf5072)


是的  就这个  点中间的ok  没作用   上下左右正常

**Comment by liuchuancong** [comment]
@sleel  有没有键值说明 或者问问厂商 
 0x1c 31  # S-POWERMENU (POWER)
    0x01 164 # PLAYPAUSE (TV)
    0x5f 113 # MUTE (KBUTTON)
    0x4b 168 # REWIND (|<<)
    0x4f 208 # FASTFORWARD (>>|)
    0x47 105 # LEFT
    0x07 106 # RIGHT
    0x1a 103 # UP
    0x48 108 # DOWN
    0x06 28  # ENTER (OK)
    0x42 102 # HOME (HOUSE)
    0x0a 14  # BACKSPACE (BACK ARROW)
    0x18 46  # CONTEXTMENU (DOCUMENT)
    0x0c 11  # KEY No.0
    0x54 2   # KEY No.1
    0x16 3   # KEY No.2
    0x15 4   # KEY No.3
    0x50 5   # KEY No.4
    0x12 6   # KEY No.5
    0x11 7   # KEY No.6
    0x4c 8   # KEY No.7
    0x0e 9   # KEY No.8
    0x0d 10  # KEY No.9
    0x10 24  # O-CODEC INFO (BACKSPACE)
    0x41 23  # INFO (GLOBE)
    0x5c 114 # VOLUMEDOWN (VOL-)
    0x5d 115 # VOLUMEUP (VOL+)

类似于这种出厂配置

**Comment by sleel** [comment]
> @sleel 有没有键值说明 或者问问厂商 0x1c 31 # S-POWERMENU (POWER) 0x01 164 # PLAYPAUSE (TV) 0x5f 113 # MUTE (KBUTTON) 0x4b 168 # REWIND (|<<) 0x4f 208 # FASTFORWARD (>>|) 0x47 105 # LEFT 0x07 106 # RIGHT 0x1a 103 # UP 0x48 108 # DOWN 0x06 28 # ENTER (OK) 0x42 102 # HOME (HOUSE) 0x0a 14 # BACKSPACE (BACK ARROW) 0x18 46 # CONTEXTMENU (DOCUMENT) 0x0c 11 # KEY No.0 0x54 2 # KEY No.1 0x16 3 # KEY No.2 0x15 4 # KEY No.3 0x50 5 # KEY No.4 0x12 6 # KEY No.5 0x11 7 # KEY No.6 0x4c 8 # KEY No.7 0x0e 9 # KEY No.8 0x0d 10 # KEY No.9 0x10 24 # O-CODEC INFO (BACKSPACE) 0x41 23 # INFO (GLOBE) 0x5c 114 # VOLUMEDOWN (VOL-) 0x5d 115 # VOLUMEUP (VOL+)
> 
> 类似于这种出厂配置

出口山寨厂商 店铺都没有了  我网上找找

**Comment by liuchuancong** [comment]
@sleel  我打个包你测试一下 ok建是啥吧

**Comment by liuchuancong** [comment]
@sleel  https://www.123pan.com/s/Jucxjv-NwYYd.html  其他工具里面你打开安装拍个图片上传一下

**Comment by sleel** [comment]
老哥  我找了下 本机的遥控器配置文件remote.conf 你看看有用吗

#*********************************************************************************************************
#this file is configuration for each factory remote device
# 	work_mode	  0 :software mode  1 :hardware mode
#	repeat_enable	  0 :disable repeat 1 :enable repeat
#
#	factory_code      each device has it's unique factory code.
#			  pattern:custom_code(16bit)+index_code(16bit)
#			  examble: 0xff000001 = 0xff00(custom cod)  0001 (index)
#
#	release_delay	  unit:ms.release will report from kernel to user layer after this period of time
#			  from press or repeat triggered.
#
#	debug_enable      0 :debug disable  1 :debug disable
#
# SW MODE:
#	bit_count	  how many bits in each frame
#	tw_leader_act	  time window for leader active
#	tw_bit0		  time window for bit0 time.
#	tw_bit1		  time window for bit1 time
#	tw_repeat_leader  time window for repeat leader
# REG
#	reg_base_gen	  set value for PREG_IR_DEC_BASE_GEN
#	reg_control	  set value for PREG_IR_DEC_CONTROL
#	reg_leader_act	  set value for PREG_IR_DEC_LEADER_ACTIVE
#	reg_leader_idle	  set value for PREG_IR_DEC_LEADER_IDLE
#	reg_repeat_leader set value for PREG_IR_DEC_REPEAT_IDLE
#	reg_bit0_time	  set value for PREG_IR_DEC_BIT0_TIME
#*************************************************************************************************************
#amlogic NEC remote
factory_code	= 0x40400001
work_mode  		= 0
repeat_enable = 1
repeat_delay = 130
repeat_peroid = 120
release_delay   =       20
debug_enable 	= 1

fn_key_scancode    = 0x47
left_key_scancode  = 0x10
right_key_scancode = 0x11
up_key_scancode    = 0x0b
down_key_scancode  = 0x0e
ok_key_scancode    = 0x0d

mouse_begin
		0 0x10
		1 0x11
		2 0x0b
		3 0x0e
mouse_end

key_begin
    0x43 113 #MUTE

    0x01 2 #No.1 
    0x02 3 #No.2
    0x03 4 #No.3
    0x04 5 #No.4
    0x05 6 #No.5
    0x06 7 #No.6
    0x07 8 #No.7
    0x08 9 #No.8
    0x09 10 #No.9
    0x00 11 #N0.0

    0x45 125 #MENU
    0x42 1   #BACK/EXIT
    
    0x0d 97  #ENTER/OK
    0x10 105 #LEFT
    0x0b 103 #UP
    0x0e 108 #DOWN
    0x11 106 #RIGHT

    0x18 115 #VOL+
    0x17 114 #VOL-
    
    0x0c 14  #DEL
    
    0x4d 116 #Power

    0x1a 102 #home
    0x53 119 #media_pause
    0x44 52 #period
    
    0x1e 123   #MEDIA_NEXT
    0x1f 122   #MEDIA_PREVIOUS
    0xf1 140   #F10/factory_test
    0x54 150   #setting
    0x57 151   #PROG_YELLOW/EXPLORER
    0x5b 152   #PROG_BLUE/MUSIC
    0x5c 153   #ALLAPP
    0x5d 154   #MEDIAPLAY
    0x5e 159   #KODI
    0x66 217   #SEARCHSEARCH
key_end
repeat_key_begin
    0x43 113 #MUTE

    0x01 2 #No.1 
    0x02 3 #No.2
    0x03 4 #No.3
    0x04 5 #No.4
    0x05 6 #No.5
    0x06 7 #No.6
    0x07 8 #No.7
    0x08 9 #No.8
    0x09 10 #No.9
    0x00 11 #N0.0

    0x45 125 #MENU
    0x42 1   #BACK/EXIT
    
    0x0d 97  #ENTER/OK
    0x10 105 #LEFT
    0x0b 103 #UP
    0x0e 108 #DOWN
    0x11 106 #RIGHT

    0x18 115 #VOL+
    0x17 114 #VOL-
    
    0x0c 14  #DEL
    
    0x4d 116 #Power

    0x1a 102 #home
    0x44 52 #period

    0x1e 120   #MEDIA_FAST_FORWARD
    0x1f 121   #MEDIA_REWIND
    0x54 150   #setting
    0x57 151   #PROG_YELLOW/EXPLORER
    0x5b 152   #PROG_BLUE/MUSIC
    0x5c 153   #ALLAPP
    0x5d 154   #MEDIAPLAY
    0x5e 159   #KODI
    0x66 217   #SEARCHSEARCH
repeat_key_end

**Comment by liuchuancong** [comment]
@sleel  作用不大 需要你的遥控器的keyCode

**Comment by sleel** [comment]
![916E4829-B5EB-4BB3-9BCB-688D60C429FF](https://github.com/liuchuancong/pure_live/assets/30924409/69137430-85f9-48c6-ab4e-64b1cb707d46)

是这样的吗？

**Comment by liuchuancong** [comment]
@liuchuancong 不太对

**Comment by sleel** [comment]
@liuchuancong 我也感觉不太对   按那个都是up  然后down  显示都一样

**Comment by liuchuancong** [comment]
你重新下载一下安装一下 或者左右按一下 @sleel

**Comment by liuchuancong** [comment]
这个没有具体的值很奇怪

**Comment by liuchuancong** [comment]
我更新来一个新的具体打印的内容

**Comment by sleel** [comment]
![AE46C5BF-014F-45C6-AD8D-295D096211C5](https://github.com/liuchuancong/pure_live/assets/30924409/e26a66ca-ae10-4f47-ad0d-c9fd562fa56e)


新版内容

**Comment by liuchuancong** [comment]
不知道为啥就是无法打印内容

**Comment by liuchuancong** [comment]
@sleel 我上传了个新安装包  的你试一下看可以不  直接安装电视版

**Comment by liuchuancong** [comment]
1.7.1版本

**Comment by sleel** [comment]
刚下载的1.71  还是不行  老哥  别急过周末去吧

**Comment by liuchuancong** [comment]
@sleel  重新在安装一下试试  键盘测试工具 这次应该好了

**Comment by liuchuancong** [comment]
![Uploading image.png…]()
需要这个东西，我这是Android 模拟器

**Comment by sleel** [comment]
![94C62236-DB2A-4B16-8891-3A0E995A9644](https://github.com/liuchuancong/pure_live/assets/30924409/cbdb876f-ed2c-453e-9ca8-fa1a55693b33)
![CECEF77C-6E33-4F8C-89E7-826249CEC575](https://github.com/liuchuancong/pure_live/assets/30924409/f6540518-b3b5-4ecd-b8fe-66437914cf96)
![2E0EB19D-3AAD-4491-9C59-87A81C5235D5](https://github.com/liuchuancong/pure_live/assets/30924409/6ff03f10-957d-44cf-9973-ffae7bd49d35)
![2FFA4FC6-0309-4C90-A325-D99E4793B506](https://github.com/liuchuancong/pure_live/assets/30924409/1cd6c211-bb6b-4852-913a-e02832795a37)
![4B8FEFD6-4907-4AF3-B400-4E392A625F6B](https://github.com/liuchuancong/pure_live/assets/30924409/00dfc8f2-f508-47a3-b7b6-831836e7ff43)
![D7E13EFD-E1EE-4B66-AAEF-D4D23443186C](https://github.com/liuchuancong/pure_live/assets/30924409/42ade0ed-360f-4de0-bfa3-fa20632958fd)


感觉找到问题了   图1是按下ok  图2是松开ok  返回两个值   上下左右都是一个   老哥牛🐮

**Comment by liuchuancong** [comment]
@sleel  重新安装一下试试

**Comment by sleel** [comment]
@liuchuancong
妥了啊  性感老哥 在线Coding!  牛

**Comment by sleel** [comment]
现在就差个 atv首页的图标了
