### ISSUE TITLE
希望作者大大加个删除m3u直播源的功能，一些失效的源能手动删除

### ISSUE THREAD

**Issue by MoRanHongChenLT** [liuchuancong/pure_live#172]
![image](https://github.com/liuchuancong/pure_live/assets/120862503/b463d61b-d840-4995-91b3-d849cb9af0f3)

**Comment by liuchuancong** [comment]
@MoRanHongChenLT   Android端在缓存内清除缓存即可删除
Windows 在目录C:/Users/用户名/AppData/Local/com.example/pure_live下categories.json内修改以及删除导入的源以及定义

**Comment by MoRanHongChenLT** [comment]
ok！已解决
