### ISSUE TITLE
(Bug)播放器问题

### ISSUE THREAD

**Issue by dzlea** [liuchuancong/pure_live#173]
![Screenshot_20240529-202540.jpg](https://github.com/liuchuancong/pure_live/assets/54771820/42b634d9-23fb-4f85-b219-e0eadc0cea4f)

exo播放器无法播放，1.6.8版本可以，其余几个除了系统播放器也不能播放，其余都可以播放，但是mpvplayer音频和视频不同步

**Comment by Her-Joe** [comment]
我也是这个问题，之前提示更新1.69就无法播放，就退回到1.68了，最近1.68虎牙用不了就升级到1.71问题依旧
不同播放器，硬软解码都切换过，没用
机型是三星s10

老哥issues没解决就别关吧
大家一起来反馈一下情况更容易找到问题原因呀T^T
