### ISSUE TITLE
bug 全屏按钮

### ISSUE THREAD

**Issue by kanao7** [liuchuancong/pure_live#174]
(补:ijk和阿里都正常，mpv存在这个bug)自1.69版本开始，进入全屏按钮需点击两次，导致控制按钮显示bug,在手机和pad复现。望修复
![Screenshot_20240530_003023_com mystyle purelive](https://github.com/liuchuancong/pure_live/assets/61642717/2c56503b-9d72-4518-8744-77f90856d3ec)

**Comment by kanao7** [comment]
![Screenshot_20240530_003008_com mystyle purelive](https://github.com/liuchuancong/pure_live/assets/61642717/e6b56e31-700b-4642-8787-791e66d0e5c5)

**Comment by kanao7** [comment]
![Screenshot_20240530_003843_com mystyle purelive](https://github.com/liuchuancong/pure_live/assets/61642717/62fff561-8033-4c4b-9790-000b0a31bc40)

**Comment by liuchuancong** [comment]
mpv 用的第三方包，等更新吧
