### ISSUE TITLE
阿斗歸來了無法播放

### ISSUE THREAD

**Issue by chenhy66tw** [liuchuancong/pure_live#175]
大哥，1.7.0版本阿斗歸來了無法直播，請修正

**Comment by chenhy66tw** [comment]
止戈電影，科幻夢工廠直播也都無法播放

**Comment by chenhy66tw** [comment]
只有阿里播放器可正常播放

**Comment by liuchuancong** [comment]
那就切换播放器吧，exo ali ijk 用的一样的配置，放不出来暂时也没啥好办法

**Comment by liuchuancong** [comment]
那就切换播放器吧，exo ali ijk 用的一样的配置，放不出来暂时也没啥好办法
