### ISSUE TITLE
新版本自动退出。

### ISSUE THREAD

**Issue by neuopzx** [liuchuancong/pure_live#177]
系统:  晶辰s905x3  a55核心  32位安卓。

新版本1.69  1.70没有用过。
后来虎牙不能用后，安装了1.71 的tv低版本。
进了app后会出现自动退出现象，
如不出现进入app后自动退出现象，则会在打开直播间时自动退出。

解决办法，打开自动退出，则多进几次。
进入直播间自动退出，则需要更换播放器，在那4个播放器中一直换，直到不退出为止。
并且不固定哪个播放器退出，哪个播放器正常播放。一切都是不确定的。
并且每次打开都会自动退出，反复试多遍才正常便用。退出app重新打开后，继续自动退出。

**Comment by liuchuancong** [comment]
切换播放器后退出的话把App退出一下重新打开

**Comment by liuchuancong** [comment]
目前的播放器表面上切换了内核但是实际上还是有问题 还需要解决
