### ISSUE TITLE
一直不能播放

### ISSUE THREAD

**Issue by xming521** [liuchuancong/pure_live#178]
所有直播都是
![Screenshot_2024-06-06-18-41-49-374_com.mystyle.purelive.jpg](https://github.com/liuchuancong/pure_live/assets/32786500/1232a879-286e-4955-a6f9-bfbc817f4902)

![Screenshot_2024-06-06-18-41-44-905_com.mystyle.purelive.jpg](https://github.com/liuchuancong/pure_live/assets/32786500/958051d9-e915-4a90-8639-7c86b7e5fd67)

**Comment by liuchuancong** [comment]
换个播放器重启一下 应该是新播放器有问题

**Comment by liuchuancong** [comment]
#183
