### ISSUE TITLE
播放失败的切换播放器，bilibili用IJK播放（语音房无法观看），其他的使用阿里播放器，如果仍然播放失败，请退出App重试

### ISSUE THREAD

**Issue by liuchuancong** [liuchuancong/pure_live#183]

**Comment by Tobeprmn** [comment]
真的误解，更换播放器依然无法观看B站直播。
![1](https://github.com/liuchuancong/pure_live/assets/119318291/f427c291-db9e-4650-bcc5-562ad0810bdd)
![2](https://github.com/liuchuancong/pure_live/assets/119318291/cb8a5f4f-3a4f-47c2-9c9d-e456f245183a)

**Comment by liuchuancong** [comment]
@Tobeprmn 语音房不可以查看

**Comment by Tobeprmn** [comment]
不是语音房，就是正常的视频直播，并不是某一个无法观看，是所有的都不能看

> @Tobeprmn 语音房不可以查看

**Comment by 13736171140** [comment]
电视版本无效

**Comment by liuchuancong** [comment]
> 电视版本无效

一套代码啊，我昨天使用了正常播放的

**Comment by 13736171140** [comment]
> > 电视版本无效
> 
> 一套代码啊，我昨天使用了正常播放的

电视版和手机版在手机上正常播放，在电视上无法播放，看来是电视问题了

**Comment by XyHK-HUC** [comment]
在一个手机上最新版exo播放器正常，在另一个就不行了

**Comment by liuchuancong** [comment]
选择合适的播放器 一般exo就足够了 exo看虎牙会没声音 切换路线就好了

**Comment by liuchuancong** [comment]
> 在一个手机上最新版exo播放器正常，在另一个就不行了

用mpv吧

**Comment by 13736171140** [comment]
除了B站，其他平台用阿里可以正常播放，手机上什么播放器都能
