### ISSUE TITLE
How to fullscreen in Android TV?

### ISSUE THREAD

**Issue by aiyogg** [liuchuancong/pure_live#19]
Thank you for your effort!
After installing your app, it can run perfectly on the projector. However, there is a small issue. I don't know how to enter full-screen mode on the live streaming playback interface. I'm not sure if the app supports full-screen on Android TV or if I am doing something wrong?
感谢作者的付出！
安装你的APP后，可以完美的运行在投影仪上，但是有个小问题，直播播放界面不知道如何进入全屏模式。不知道是否APP在Android TV上支持全屏，或者我有任何操作不当？

**Comment by aiyogg** [comment]
Specific issue at present: On the playback interface, it is not possible to bring up the playback menu using the remote control, thus unable to select full screen.
当前具体的问题：：在播放界面，无法通过遥控器呼出播放菜单，因而无法选中全屏；

**Comment by liuchuancong** [comment]
你可以打开设置自动全屏即可，TV端目前ui无法正常操作只能粗略控制。

**Comment by liuchuancong** [comment]
使用邮箱登录设置配置上传后即可自动同步

**Comment by aiyogg** [comment]
感谢回复。我在设置里看到了这个设置项，可以解决我的问题。
进入播放页面遥控器只能退出播放和加减音量，关注主播选不到不知道有没有解决方案。
再次感谢你的付出。

**Comment by liuchuancong** [comment]
在次点击返回就可以了，我的极光盒子是可以切换的
