### ISSUE TITLE
1.7.2被360误报了

### ISSUE THREAD

**Issue by GhostX123** [liuchuancong/pure_live#190]
之前好像不会，目前已经添加信任，360最近抽风的越来越厉害，上周从amd官网下的芯片组驱动都被360报毒，简直逆天
![image](https://github.com/liuchuancong/pure_live/assets/52536642/d3ef2882-238e-4187-8013-14db4d164331)
下图是当时安装amd芯片组驱动产生的临时文件被360报毒
![image](https://github.com/liuchuancong/pure_live/assets/52536642/81815960-70fe-4c9c-a1a4-fbe393aeadd7)
大佬看到就close吧，我就是来吐槽一下360的

**Comment by liuchuancong** [comment]
没有备案估计都会报

**Comment by xzy666666** [comment]
> 没有备案估计都会报

平时喜欢捣鼓各种软件不能裸奔，WD太难用，火绒不搞自定义规则也不好用，准备转sandboxie沙箱了
