### ISSUE TITLE
某些平台不开播的主播无法搜索

### ISSUE THREAD

**Issue by SQSora** [liuchuancong/pure_live#191]
某些平台不开播的主播无法搜索，希望可以加一个输入房间号就能直接跳转的功能

**Comment by SQSora** [comment]
其他平台是可以的，但是网页版抖音就需要手动拼接一下。
另外我更新到了1.7.2版本，基本都不能播放。我回退到1.6.4就好了

**Comment by wendong597** [comment]
> 其他平台是可以的，但是网页版抖音就需要手动拼接一下。另外我更新到了1.7.2版本，基本都不能播放。 我回退到1.6.4就好了

抖音用电脑网页端链接和官方客户端里面直接复制链接

**Comment by SQSora** [comment]
"另外我更新到了1.7.2版本，基本都不能播放。我回退到1.6.4就好了" 是指全部平台的主播都卡不了。有的可能就播放几秒就一直在重试播放

**Comment by wendong597** [comment]
> "另外我更新到了1.7.2版本，基本都不能播放。 我回退到1.6.4就好了" 是指全部平台的主播都卡不了。 有的可能就播放几秒就一直在重试播放


更换播放器试试，手机端用阿里和mpv，电视端阿里 和exo
