### ISSUE TITLE
安卓1.1.9斗鱼全屏无法播放

### ISSUE THREAD

**Issue by mingxitang** [liuchuancong/pure_live#2]

**Comment by liuchuancong** [comment]
重启试试，我这里没问题

**Comment by mingxitang** [comment]
重启没用，不是完全无法播放，是进入全屏后播放十多秒后卡顿，刷新后无法播放

**Comment by liuchuancong** [comment]
> 重启没用，不是完全无法播放，是进入全屏后播放十多秒后卡顿，刷新后无法播放

@mingxitang  应该是直播流的问题，我点开大部分是可以播放的，但是有的还是黑屏

**Comment by liuchuancong** [comment]
你试试在斗鱼能看不，已经下播了的或者是斗鱼也无法观看的是看不了的，之前出现过一次直播流卡顿，是平台的问题

**Comment by liuchuancong** [comment]
@mingxitang 那应该是播放器和你的手机不兼容，目前新的播放器windows使用了支持良好，android不支持画中画以及后台播放故保留旧的播放器，新的播放器Android版支持画中画会进行更新的

**Comment by liuchuancong** [comment]
@mingxitang 没有有试过别的平台全屏可以播放吗

**Comment by mingxitang** [comment]
> @mingxitang 没有有试过别的平台全屏可以播放吗

除了斗鱼，其他都行

**Comment by liuchuancong** [comment]
播放器公用的，和平台无关，目前无法确定原因

**Comment by mingxitang** [comment]
> 播放器公用的，和平台无关，目前无法确定原因

好的，谢谢

**Comment by mingxitang** [comment]
1.22的新播放器可以用了，谢谢

**Comment by mingxitang** [comment]
> 1.22的新播放器可以用了，谢谢

播放器的问题1.24，换回exoplayer后，斗鱼无法播放
