### ISSUE TITLE
1.7.3 pc端基本不可用

### ISSUE THREAD

**Issue by M1NGc** [liuchuancong/pure_live#202]
状态不对，只显示2个正在直播   雷军其实没在播
 ![image](https://github.com/user-attachments/assets/d1a2938b-488a-4123-afad-faf85aaf746c)
一直卡刷新
![image](https://github.com/user-attachments/assets/1ff05036-1ab6-4a0b-b0d5-ad009aee4946)

太多太多

**Comment by linccue** [comment]
windows版本哔哩哔哩希望能够修复，开播的看不了

**Comment by M1NGc** [comment]
找到问题了   旧版本保留的配置文件  应用到新版本时有问题

**Comment by M1NGc** [comment]
1.7.4还是不行  ![image](https://github.com/user-attachments/assets/db937ead-cc6d-4336-9cec-6622ce9f058b)
