### ISSUE TITLE
1.7.4 链接解析-抖音

### ISSUE THREAD

**Issue by M1NGc** [liuchuancong/pure_live#205]
抖音app直播间复制的网址  https://v.douyin.com/irfnQn8d/   直播解析不了
https://v.douyin.com/irfnQn8d/   在浏览器打开地址变成https://live.douyin.com/799918853115?from=web_code_link  这个地址直播可以解析

**Comment by wendong597** [comment]
> 抖音app直播间复制的网址https://v.douyin.com/irfnQn8d/ 直播解析不了 https://v.douyin.com/irfnQn8d/ 在浏览器打开地址变成https://live.douyin.com/799918853115?from=web_code_link 这个地址直播可以解析

你这抖音APP的链接复制的都不完整，最后面的肯定被你删了吧

**Comment by liuchuancong** [comment]
@M1NGc  链接不完整
8- #在抖音，记录美好生活#【吞金兽】正在直播，来和我一起支持Ta吧。复制下方链接，打开【抖音】，直接观看直播！ https://v.douyin.com/irPCWh4J/ 4@1.com :1pm  类似这种
