### ISSUE TITLE
平板和电视所有平台无法进行正常播放

### ISSUE THREAD

**Issue by leekinger** [liuchuancong/pure_live#208]
![image](https://github.com/user-attachments/assets/da97a57a-2102-45a8-b9d9-1c1387ce1869)
平板为xiaomi平板6，电视为xiaomi mini led ,手机小米14正常使用，电视平板回退173，172都无效

**Comment by liuchuancong** [comment]
@leekinger 自动切换 有bug 会导致UI卡死 需要重启一下

**Comment by leekinger** [comment]
重启机器吗，试过没效果

**Comment by liuchuancong** [comment]
mpv播放器

**Comment by liuchuancong** [comment]
设置
