### ISSUE TITLE
快手是不是用不了

### ISSUE THREAD

**Issue by yuf19-2022** [liuchuancong/pure_live#214]

**Comment by liuchuancong** [comment]
快手有风控 会限制请求Ip 要稍等请求 最好不要刷新直接进

**Comment by liuchuancong** [comment]
> > 快手有风控 会限制请求Ip 要稍等请求 最好不要刷新直接进
> 
> 我是搜索直播，搜不到，搜什么都搜不到

官网不登陆不是也搜不到吗
