### ISSUE TITLE
竖屏直播全屏是横屏显示

### ISSUE THREAD

**Issue by raylizw** [liuchuancong/pure_live#215]
竖屏的直播点全屏是横屏显示，不知道好不好弄
![IMG_20240928_002021](https://github.com/user-attachments/assets/737739d8-6183-4748-af3f-4c2ef70fc8e6)
![Screenshot_2024-09-28-00-17-57-667_com mystyle purelive](https://github.com/user-attachments/assets/cb7a65a2-c15f-41d3-b24d-831ddcd4f5b2)
我这里播放器只有选mpv能用了，选其他的都播放失败
![Screenshot_2024-09-28-00-14-12-739_com mystyle purelive-edit](https://github.com/user-attachments/assets/1e66be5a-5b8b-4ffd-a411-5f4c33821aa7)

**Comment by raylizw** [comment]
后台播放好像也有问题

**Comment by wendong597** [comment]
> 竖屏的直播点全屏是横屏显示，不知道好不好弄 ![IMG_20240928_002021](https://private-user-images.githubusercontent.com/52343240/371608950-737739d8-6183-4748-af3f-4c2ef70fc8e6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MzA5NjMsIm5iZiI6MTcyNzUzMDY2MywicGF0aCI6Ii81MjM0MzI0MC8zNzE2MDg5NTAtNzM3NzM5ZDgtNjE4My00NzQ4LWFmM2YtNGMyZWY3MGZjOGU2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDEzMzc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTk3ODNkZDYwYjI1ZTY4ODU1MDBkZDc2ZjFmMTJkNGI2NThkYzAzYmZmNmE1NGIxNTc0MzZkNzlkOTViMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6ClvkD0ETXIhtsXexLERoVSkA0eVQgowwFUnbflssus) ![Screenshot_2024-09-28-00-17-57-667_com mystyle purelive](https://private-user-images.githubusercontent.com/52343240/371608966-cb7a65a2-c15f-41d3-b24d-831ddcd4f5b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MzA5NjMsIm5iZiI6MTcyNzUzMDY2MywicGF0aCI6Ii81MjM0MzI0MC8zNzE2MDg5NjYtY2I3YTY1YTItYzE1Zi00MWQzLWIyNGQtODMxZGRjZDRmNWIyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDEzMzc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMDc5MTk0MjNkYTVhZGMwNjE5YjkwNTQ2MzRjYjEyNWYzNzY2YTBhZDYyMjIyNTUyNDJjMDQxZTI4MTI2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pUvIVKhIXc3lh5KbM-S5EwN6XtUP0vKxm8e5KBLp-Rg)我这里播放器只有选mpv能用了，选其他的都播放失败 ![Screenshot_2024-09-28-00-14-12-739_com mystyle purelive-edit](https://private-user-images.githubusercontent.com/52343240/371609123-1e66be5a-5b8b-4ffd-a411-5f4c33821aa7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MzA5NjMsIm5iZiI6MTcyNzUzMDY2MywicGF0aCI6Ii81MjM0MzI0MC8zNzE2MDkxMjMtMWU2NmJlNWEtNWI4Yi00ZmZkLWE0MTEtNWY0YzMzODIxYWE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDEzMzc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNjlkMzIxMjIyZTgwYzA3OTlhMWJhMTlkYzE2ZmViNjk0YzMwMDY2YTg0ZWQ4ZjM0NzNjYTRmMDMyMTBmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.apH-s5qzNGl-YezfstB8EQJoCmrIovwnRvFGTw-BfCg)

换个播放器的事，阿里或者ijk
