### ISSUE TITLE
手机无法播放

### ISSUE THREAD

**Issue by JacksonZhong-official** [liuchuancong/pure_live#216]
手机端显示无法播放直播，重启、切换清晰度和线路都没用

**Comment by liuchuancong** [comment]
切换播放器 app杀了重启

**Comment by JacksonZhong-official** [comment]
好了！！！大佬牛逼！！！




Jackson
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuchuancong/pure_live"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月15日(星期二) 中午12:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuchuancong/pure_live] 手机无法播放 (Issue #216)





 
切换播放器 app杀了重启
