### ISSUE TITLE
安卓最新版，抖音无法显示弹幕

### ISSUE THREAD

**Issue by linccue** [liuchuancong/pure_live#217]
如题
![Screenshot_2024-10-15-15-22-20-142_com mystyle purelive](https://github.com/user-attachments/assets/2ed1f1b9-eec8-4685-9f37-253da9f7f63d)

**Comment by linccue** [comment]
试过重启，无效，版本号1.7.1

**Comment by linccue** [comment]
安卓14，hyperos

**Comment by liuchuancong** [comment]
@linccue 下载最新版
