### ISSUE TITLE
LJK播放器返回前台后有声音但黑屏

### ISSUE THREAD

**Issue by linccue** [liuchuancong/pure_live#218]
是我有哪里没调好吗？已经打开了后台播放，锁住后台。将软件放置后台再回到前台后，直播一直有声音但画面黑屏。
尝试过其他播放器，exo后台会暂停播放
1.7.4，hyperos

**Comment by liuchuancong** [comment]
所有的播放器都这样，是播放器的问题，gsy_video_player导致的，重新刷新下就好了
