### ISSUE TITLE
tv端的1.7.4低版本，快手直播的弹幕功能失效

### ISSUE THREAD

**Issue by XZXZZZ** [liuchuancong/pure_live#220]
tv端1.7.4低版本的b站，斗鱼，虎牙的弹幕都能正常显示，但快手直播的弹幕功能不可用，同时也尝试了tv端其他版本，快手直播的弹幕功能都不可用

**Comment by XZXZZZ** [comment]
b站，斗鱼，虎牙的弹幕都能显示，但快手的弹幕功能不可用

**Comment by liuchuancong** [comment]
快手不登录看不了弹幕 也没做弹幕

**Comment by XZXZZZ** [comment]
> 快手不登录看不了弹幕 也没做弹幕

感谢解答，不过我第一次装一个1.4.几还是1.5.几的时候，我记得我看快手的时候是有弹幕的，后来我换其他版本又没有了，所以我才以为是有bug了

**Comment by liuchuancong** [comment]
> > 快手不登录看不了弹幕 也没做弹幕
> 
> 感谢解答，不过我第一次装一个1.4.几还是1.5.几的时候，我记得看快手的时候是有弹幕的，后来我换其他版本又没有了，请问是否有某个版本是能看弹幕的？或者是之前快手不用登陆也能看弹幕？

所有的都没有弹幕

**Comment by lishuzhi666** [comment]
期待大佬可以增加登录之后看弹幕的功能
