### ISSUE TITLE
tv端能增加一个兼容模式吗？

### ISSUE THREAD

**Issue by wtjperi2003** [liuchuancong/pure_live#221]
pure_live在我家索尼电视上无法播放。dart_simple_tv启用兼容模式时可以正常播放。我看了下代码就是media player添加几个属性而已

**Comment by liuchuancong** [comment]
@wtjperi2003 使用硬解码

**Comment by wtjperi2003** [comment]
> @wtjperi2003 使用硬解码

都试过了，不行

**Comment by liuchuancong** [comment]
@wtjperi2003 网盘重新下一下 换阿里播放器

**Comment by wtjperi2003** [comment]
@liuchuancong 

好吧，我周末试试
