### ISSUE TITLE
UI建议

### ISSUE THREAD

**Issue by li5bo5** [liuchuancong/pure_live#225]
切换平台有点麻烦
![image](https://github.com/user-attachments/assets/41b0bbf6-6576-4fde-a513-7e083254e09d)
简单做了一下UI，感觉这样会更简单，操作更便捷
把收藏、历史记录、全部放“我的”里面，
热门推荐放在每个平台的首页
app启动界面支持可调，比如我启动进入历史记录，别人启动进入收藏
如果可以的话，几个平台支持调整排序就更好了
有没有兄弟支持的？

**Comment by liuchuancong** [comment]
设备不好的会卡
