### ISSUE TITLE
一起看修复说明。

### ISSUE THREAD

**Issue by liuchuancong** [liuchuancong/pure_live#235]
1.更新至最新版。
2.在三方认证输入cookie
3.打开`https://www.huya.com/adgll`,然后点击F12，tab栏切换至console（控制台）,输入`document.cookie`,将cookie粘贴于输入框中
左右引号不要
4.点击设置
5.可使用数据同步
6.播放依然中断（请重复1-5）

**Comment by shenshei** [comment]
还是打不开，删除重新安装无数次了，win10用那俩包都不行

**Comment by VehiclePP** [comment]
> 5.可使用数据同步

这个什么意思？

**Comment by VehiclePP** [comment]
> 使用数据同步

1-4试了很多次，还是不行。。。
