### ISSUE TITLE
1.7.7安装后打不开

### ISSUE THREAD

**Issue by wtjperi2003** [liuchuancong/pure_live#238]
如题，win11系统

**Comment by girlNormal** [comment]
> 如题，win11系统

我也遇到了，解决不了。。。我重装了也没解决，双击以后没有反应。。。

**Comment by linmuwosai** [comment]
一样，我还以为系统问题，昨晚特意重装系统还是打不开

**Comment by liuchuancong** [comment]
是不是升级导致的，目前 版本Windows 11, version 22H2，打开没有问题，目前也不知道怎么处理

**Comment by linmuwosai** [comment]
> 是不是升级导致的，目前 版本Windows 11， version 22H2，打开没有问题，目前也不知道怎么处理

感觉应该是这次升级到24H2 26100.2454 导致

**Comment by linmuwosai** [comment]
看了下系统日志 

出错应用程序名称： pure_live.exe，版本： 1.7.8.0，时间戳： 0x674ed05e
出错模块名称： ucrtbase.dll， 版本： 10.0.26100.1882，时间戳： 0x52db7a2d
异常代码： 0xc0000409
错误偏移： 0x00000000000a502e
出错进程 ID： 0xE40
出错应用程序开始时间： 0x1DB4569347DD8D0
Faulting 应用程序路径： C:\Program Files\WindowsApps\com.flutter.purelive_1.0.0.70_x64__se85sd63hcrtp\pure_live.exe
Faulting 模块路径： C:\Windows\System32\ucrtbase.dll
Report ID： 07213014-0cc0-42d9-97db-829d9ec7f376
Faulting 包全名： com.flutter.purelive_1.0.0.70_x64__se85sd63hcrtp
Faulting 程序包相对应用程序 ID： PURELIVE 个

**Comment by linmuwosai** [comment]
故障存储段 2132226147710414497，类型 5
事件名称: MoBEX
响应: 不可用
Cab ID: 0

问题签名:
P1: com.flutter.purelive_1.0.0.70_x64__se85sd63hcrtp
P2: praid:PURELIVE
P3: 1.7.8.0
P4: 674ed05e
P5: ucrtbase.dll
P6: 10.0.26100.1882
P7: 52db7a2d
P8: 00000000000a502e
P9: c0000409
P10: 0000000000000007

**Comment by geekswg** [comment]
1.7.8，24h2 好像还是打不开，只能用1.7.5的版本

**Comment by wtjperi2003** [comment]
对比下1.7.5版本看看代码做了哪些更改

**Comment by liuchuancong** [comment]
@wtjperi2003 @geekswg @girlNormal @twodoging 试试网盘的178+1 我恢复了依赖 如果仍然不行 那就是电脑升级导致的不兼容

**Comment by geekswg** [comment]
可以打开了，正常了
