### ISSUE TITLE
登录后B站播放问题

### ISSUE THREAD

**Issue by Chokppl** [liuchuancong/pure_live#24]
①使用二维码登录账号后打开任意B站直播会转圈一会儿显示“无法播放直播”提示，1s后软件自行刷新可正常播放，对于体验来讲有些不连贯。
②竖屏状态正常播放直播如果双击直播区域可进行横屏很好，但触发双击手势切换横竖屏后大概率直播流会自行刷新，体验也有些割裂。

**Comment by liuchuancong** [comment]
无法播放直播 是b站获取的视频流无法播放，有时候可以播放，会自动切换， 双击屏幕是切换全屏，所有平台都一样，自行刷新是监听了Android onResume 因为如果不能后台播放，视频会被暂停，再次打开APP会有延迟。

**Comment by Chokppl** [comment]
> 无法播放直播 是b站获取的视频流无法播放，有时候可以播放，会自动切换， 双击屏幕是切换全屏，所有平台都一样，自行刷新是监听了Android onResume 因为如果不能后台播放，视频会被暂停，再次打开APP会有延迟。

第一个问题我发现是B站很多直播间在我的网络下，线路一都是无效的状态，所以在出现无法播放提示后APP自行切换到线路二后正常可播放。
第二个在另一台安卓7.1的备机上没有这个体验，安卓13的机器会出现……
现在这个登录方案是不是不建议多设备下使用，我发现有概率会掉登录。
