### ISSUE TITLE
快手直播源失效

### ISSUE THREAD

**Issue by XZXZZZ** [liuchuancong/pure_live#240]
前几天快手直播进行了画质更新，现在tv端所有快手直播间都打不开了，请问大佬能抽空维护一下吗？感谢🙏

**Comment by liuchuancong** [comment]
下载最新的不可以吗

**Comment by XZXZZZ** [comment]
> 下载最新的不可以吗

红米电视下载最新的1.7.8低版本，快手直播可以看了，感谢大佬，另外请问低版本与all和高版本有什么区别？

**Comment by liuchuancong** [comment]
处理器32和64区别
