### ISSUE TITLE
关于Windows版本的使用体验

### ISSUE THREAD

**Issue by LTQwork** [liuchuancong/pure_live#27]
基本情况：当前系统为Win11，软件版本为window-1.32.zip
状况：进入直播间只有两三秒是正常的，随后就播放失败，仅有弹幕在加载（并未全面测试，仅进入我常看的直播间，包括抖音和虎牙），失败之后就整个页面卡住。
尝试过程：1.在进入直播间时，降低画质清晰度以及切换线路。2.在主界面设置里，降低进入直播间的默认画质。
结果：播放失败，页面卡住。
最后：同版本号的Android端，未存在以上现象。

**Comment by liuchuancong** [comment]
不确定是播放器问题，可以提供直播间测试吗

**Comment by LTQwork** [comment]
你好，由于视频较大，无法上传github。我只能通过邮箱发送。




星河欲曙天
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuchuancong/pure_live"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月5日(星期天) 中午1:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuchuancong/pure_live] 关于Windows版本的使用体验 (Issue #27)





 
不确定是播放器问题，可以提供直播间测试吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

窗口 11-05-周日 15-46-02.mp4 (137.14M, 2023年12月05日 15:54 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=6435366573d85b95ef6b47131466044d4d410f5c06070f0318000254064b0106560d1b040704544f0157545251000607560c0f5d327a36d6858aec4503571b520018e0b9fab31653001802531f56044c584502650f&code=556e2f6b

**Comment by LTQwork** [comment]
目前：已覆盖更新，1.33版本依旧存在上述现象。
普遍状况：弹幕和声音都可以加载出来，画面卡住。
有些是整个页面都卡了，有个更离谱，进入直播间秒点全屏可以播放，但屏幕中心居然还是无法显示，且键盘鼠标失灵，我只能重启电脑。

**Comment by liuchuancong** [comment]
我重试也发现类似问题，目前确定是播放器内存泄露，待反馈后更新

**Comment by LTQwork** [comment]
![IMG_20231110_154201.jpg](https://github.com/liuchuancong/pure_live/assets/114479160/830d512f-e050-4ce5-bfa7-0279544000f7)

实测，1.37版本可以正常使用了（Windows），感谢作者

**Comment by liuchuancong** [comment]
@LTQwork 1.3.7没有更改任何windows播放器的代码，测试发现有的直播流会失效，比如虎牙的，就会进入自动切换直播流，不知道这样会不会导致内存增加，目前加了一个延时控制，待后期观察
