### ISSUE TITLE
找到之前播放器的bug了

### ISSUE THREAD

**Issue by mingxitang** [liuchuancong/pure_live#28]
以前有个issue， Exo播放器在斗鱼平台出现问题，其实是旧版本的备份文件导入至新版本出bug，包括此次1.33更新，覆盖安装，导致无法选择播放器，并且播放卡封面

**Comment by liuchuancong** [comment]
重新下载安装包尝试

**Comment by mingxitang** [comment]
确实是重新下载安装包，删除原软件，重新手动配置才能正常使用，但即使是新版本的备份文件，导入最新版本的应用，仍然会复现bug

**Comment by liuchuancong** [comment]
打开备份文件看下 videoIndex 那块改成0

**Comment by mingxitang** [comment]
> 打开备份文件看下 videoIndex 那块改成0

还是不行

**Comment by liuchuancong** [comment]
还有问题吗
