### ISSUE TITLE
[bug] 播放器切换上传配置后无法保存，退出软件还是切换没保存成功

### ISSUE THREAD

**Issue by dongbao66** [liuchuancong/pure_live#34]
如题

**Comment by liuchuancong** [comment]
是否有上传成功提示

**Comment by dongbao66** [comment]
> 是否有上传成功提示

有上传成功提示

**Comment by liuchuancong** [comment]
多试几次，目前没有出现

**Comment by dongbao66** [comment]
更新最新版本就可以切换了，我还以为是你修复

栋源
***@***.***




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月8日(周三) 中午11:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liuchuancong/pure_live] [bug] 播放器切换上传配置后无法保存，退出软件还是切换没保存成功 (Issue #34)




 
多试几次，目前没有出现
 
&mdash;
