### ISSUE TITLE
哔哩哔哩没有原画

### ISSUE THREAD

**Issue by checkxlo** [liuchuancong/pure_live#36]
哔哩哔哩没有原画

**Comment by dongbao66** [comment]
登录了吗  我登录了就有啊

**Comment by checkxlo** [comment]
那不是真画质哔哩哔哩要登入才能看原画，现在锁了

dongbao66 ***@***.***> 于 2023年11月6日周一 下午9:55写道：

**Comment by checkxlo** [comment]
你对比一下画质看看不是真原画

Peter Morrison ***@***.***> 于 2023年11月6日周一 下午11:46写道：

**Comment by dongbao66** [comment]
不知道是不是心理作用还是烟花  好像是有一点点的不如  感官不是很大

**Comment by dongbao66** [comment]
话说作者不是开发b站登录功能了吗  你登录了吗 我看好像跟b站原画区别不大啊

**Comment by checkxlo** [comment]
原画根本不是原画是超清

dongbao66 ***@***.***> 于 2023年11月6日周一 下午11:56写道：

**Comment by liuchuancong** [comment]
画质就是原画，差异是播放器导致的
