### ISSUE TITLE
斗鱼轮播

### ISSUE THREAD

**Issue by M1NGc** [liuchuancong/pure_live#39]
斗鱼轮播未直播的   出现在了已开播tab   之前版本是没有的
![image](https://github.com/liuchuancong/pure_live/assets/26264126/88e7a153-f62b-482a-91c8-44cf412927ef)

**Comment by liuchuancong** [comment]
目前没有轮播tab,归为在直播

**Comment by M1NGc** [comment]
> 目前没有轮播tab,归为在直播

**Comment by M1NGc** [comment]
我的意思是之前都是在未直播tab   不知道哪个版本改到了直播tab   感觉不合逻辑
