### ISSUE TITLE
[bug]安卓版本全屏页面下有竖屏右边的几个按钮图像

### ISSUE THREAD

**Issue by ruixingwu** [liuchuancong/pure_live#40]
安卓版本全屏页面下有竖屏页面右边的几个残留按钮图像
(投屏、全屏、关注)按钮的的残留图像，影响使用观感
使用原版的一直未维护的那个版本则没有问题
从全屏页面返回到竖屏页面后没有画面显示，只有声音

**Comment by Chokppl** [comment]
> 安卓版本全屏页面下有竖屏页面右边的几个残留按钮图像 (投屏、全屏、关注)按钮的的残留图像，影响使用观感 使用原版的一直未维护的那个版本则没有问题 从全屏页面返回到竖屏页面后没有画面显示，只有声音

+1
还有不知道设置里面的逻辑是什么，弹幕设置和解码器设置啥的修改后退出应用不保存的……

**Comment by liuchuancong** [comment]
使用了sufefaceview 导致的，目前还不稳定，已经还原了，可以使用mpv也很不错
