### ISSUE TITLE
网络电视优化

### ISSUE THREAD

**Issue by M1NGc** [liuchuancong/pure_live#42]
![image](https://github.com/liuchuancong/pure_live/assets/26264126/c1dc5a9f-4e92-4d41-aefe-2aae64b3875b)
这是关注后直播中的名称  显示的是地址

![image](https://github.com/liuchuancong/pure_live/assets/26264126/853c67aa-1392-44ef-b7c6-8ae3a184720d)
这是取消关注的提示一长串记忆右下角图标

**Comment by M1NGc** [comment]
![image](https://github.com/liuchuancong/pure_live/assets/26264126/2eed532d-e8d2-4d7c-82b5-d8803d8b4422)
zh这个页面可以无限往下滑

**Comment by liuchuancong** [comment]
M3u,文件无法提供准确的房间格式，只有名字和连接，当处理为房间时，只能将链接作为房间号处理，页面向下滑因为直播源太多
