### ISSUE TITLE
安卓13使用Exoplayer解码会闪退

### ISSUE THREAD

**Issue by Chokppl** [liuchuancong/pure_live#47]
最新版本。
安卓13播放除了哔哩哔哩平台都会闪退，备用机安卓7.1反而一切正常。

除了Exo解码另外两个在竖屏直播间点击全屏都会默认横屏播放。

播放解码切换后退出软件无法记忆保存每次退出会恢复为Exo解码。

建议可增加切换线路后记忆所选线路特性。以解决如哔哩哔哩平台点击直播后黑屏缓冲线路1无法播放反复切换到后续线路的问题。

**Comment by Chokppl** [comment]
> 最新版本。 安卓13播放除了哔哩哔哩平台都会闪退，备用机安卓7.1反而一切正常。
> 
> 除了Exo解码另外两个在竖屏直播间点击全屏都会默认横屏播放。
> 
> 播放解码切换后退出软件无法记忆保存每次退出会恢复为Exo解码。
> 
> 建议可增加切换线路后记忆所选线路特性。以解决如哔哩哔哩平台点击直播后黑屏缓冲线路1无法播放反复切换到后续线路的问题。

重装几次实验过后发现在安卓13下打开后台播放选项百分百闪退，关闭后正常。另一台安卓7.1的设备开关后台播放都正常使用。

**Comment by liuchuancong** [comment]
Exo 播放器为主页Better_player 其他为第三方插件，暂时无法修改。闪退可以更换默认播放器，记忆路线不现实，因为直播流和路线没有关系，直播流都有过期限制

**Comment by Chokppl** [comment]
> Exo 播放器为主页Better_player 其他为第三方插件，暂时无法修改。闪退可以更换默认播放器，记忆路线不现实，因为直播流和路线没有关系，直播流都有过期限制

闪退是从1.3.9版本开始的之前版本都是正常的……
