### ISSUE TITLE
强大的TV软件，博主加油

### ISSUE THREAD

**Issue by torynwang** [liuchuancong/pure_live#48]
以前一直想找一个直播合集软件，终于在这里找到了，软件很强大，TV端以前是没有这种软件的。博主继续加油，希望软件越做越好。另外能不能把重复弹幕过滤掉，弹幕一多了就卡，还是弹幕刷新率的问题，好像弹幕和直播有点不协调，一闪一闪的。

**Comment by liuchuancong** [comment]
电视cpu不行，弹幕过滤可以加，不做弹幕合并，消耗内存大
