### ISSUE TITLE
副屏关闭软件后，重新打开时，软件主窗口放大并出现在屏幕外。【Windows 11 版本多屏幕（主屏幕3x2 2K，副屏幕16x9 1080p）】

### ISSUE THREAD

**Issue by Ztqing** [liuchuancong/pure_live#50]
#
- 系统：
    Windows 11
- 硬件：
    - 主屏幕 3x2 2K
    - 副屏幕 16x9 1080p
- 问题：
    副屏关闭软件后，重新打开时，软件主窗口放大并出现在屏幕外。
- 原因：
    拙见是，主屏幕分辨率高，副屏幕分辨率低，再次打开时，根据记忆，窗口出现在副屏幕，但是大小记忆可能是按照主屏幕的分辨率乘上关闭时在副屏幕上占用屏幕的百分比。
---
感谢开发者对 pure_live 进行维护，功能性相比鸽了好久的原版提升了很多，Orz！

**Comment by liuchuancong** [comment]
插件限制，暂无法修改
