### ISSUE TITLE
建议提供更多同步相关的自定义选项

### ISSUE THREAD

**Issue by Ztqing** [liuchuancong/pure_live#52]
- 问题：
    我是三端都用pure_live，手机16号字体就可以了，电脑要用26号字体，平板22号就够了。就字体这块，三端需求不同。
- 建议：
    开发者提供的账号同步方式很大的方便了多端设置，不需要进行反复的导入、导出。
    **但是，希望能够提供更多的自定义选项，比如哪些部分需要同步，哪些部分不需要同步。**
    _（比如就弹幕设置而言，可以将屏蔽词与弹幕大小、范围等分开，屏蔽词进行同步、弹幕大小比例不同步等。）_

**Comment by liuchuancong** [comment]
很多用户只是一个设备，多个设备操作此类功能叠加略显复杂以及冗余，暂没有开发计划
