### ISSUE TITLE
问题反馈及功能建议

### ISSUE THREAD

**Issue by twodoging** [liuchuancong/pure_live#56]
问题反馈：

1. Android端“双击退出”功能关闭之后仅限于当前，一旦重启，会默认开启。
2. 1.41版本更新之后，网络电视无法观看，看样子需要自己找源了。

功能建议：

1. 添加直播源删除功能。只要不断的网络导入直播源，在“分区”→“网络电视”模块，会出现大量已添加的源。直播源具有时效性，绝大多数情况下，添加新源是旧源失效导致的，因此，希望可以添加删除不需要的源的功能。
2. 网络电视预览功能。像虎牙、抖音一样，有个短暂的预览。感觉每次点进去才能看到播放内容，又不能在当前频道换台，有点难受。

**Comment by liuchuancong** [comment]
已修复，直播源删除请清除缓存，目前缓存目录无需权限

**Comment by liuchuancong** [comment]
加群获取可用直播源
