### ISSUE TITLE
1.4.4版本，安卓，无法保存关于弹幕的设置

### ISSUE THREAD

**Issue by Httperrors** [liuchuancong/pure_live#58]
谢谢大佬开发这个app，我一直在用，非常感谢！
其实这个问题一直存在，那就是不管如何设置弹幕，关闭app再打开时，弹幕的设置又回到了初始状态。
希望能保存修改设定。
另外，希望默认进入直播间，弹幕是默认关闭的，谢谢

**Comment by liuchuancong** [comment]
现在数据在本地没有更新

**Comment by Httperrors** [comment]
> > 现在数据在本地没有更新
> 
> 报告一个新情况，今早晨打开显示一片白，然后就没了动静😭
> 安卓7一个平板，安装的v7版本，昨天还用的好好的

更新了1.4.5后恢复正常啦
