### ISSUE TITLE
大佬最新的版本可以让抖音默认竖屏吗

### ISSUE THREAD

**Issue by mizhihan** [liuchuancong/pure_live#6]
虽然添加了旋转按钮，但是抖音绝大部分都是竖屏的。希望能默认竖屏，遇到少部分横屏的再手动点击旋转。或者以后加入自动识别就更好啦。

**Comment by liuchuancong** [comment]
下版本douyin会自动横屏

**Comment by drw2005** [comment]
> 下版本douyin会自动横屏

应该是默认竖屏啊，抖音还是竖屏的多，需要时再手动点击横屏。
