### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by hahuo** [liuchuancong/pure_live#62]
本来只是想退出弹幕设置，却退出了全屏
大佬，有没有不退出全屏的可能
如图所示

https://github.com/liuchuancong/pure_live/assets/125648416/72f509f7-3cfb-4572-933d-7e2fb38a76f3

-Fix:双击返回与单机返回.
-Fix:全屏下点击弹幕设置手势会关闭设置.
-Fix:权限管理：同步功能迁移，不对外公共开放
-Fix:双击返回与单机返回.
-Fix:全屏下点击弹幕设置手势会关闭设置.
-Fix:权限管理：同步功能迁移，不对外公共开放

**Comment by liuchuancong** [comment]
后面修复下，这个弹幕设置不是页面
