### ISSUE TITLE
能不能增加一个调节音量的功能

### ISSUE THREAD

**Issue by Echoovo** [liuchuancong/pure_live#63]
就是在直播页面直接可以调节音量，而且和系统音量分离，并且大佬有做小窗的计划吗，经常就是同时开几个直播间...

**Comment by Echoovo** [comment]
好像可以滑动调节音量。。那主要是和系统音量分离和小窗了。。。或者加个音量调节按钮？

**Comment by liuchuancong** [comment]
目前没有多开直播间的打算，后面也没有计划开发，音量可以滑动调节或者使用系统调节按钮

**Comment by Echoovo** [comment]
那如果能和系统音量分离就好了...滑动调节经常把系统音量一起改了就有点不太方便就是...
