### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hsichien** [liuchuancong/pure_live#64]
1.4.7版本，全面屏手势下在直播页面中触发返回手势依旧会直接退出app到桌面

**Comment by liuchuancong** [comment]
侧滑和上滑是不一样的手势

**Comment by Resurrection2981** [comment]
原生 Android 14，在所有页面中（包括设置），侧滑返回都是直接回桌面

**Comment by hsichien** [comment]
> 侧滑和上滑是不一样的手势

但是现在侧滑和上划实际的触发效果一样了,都是返回到桌面

**Comment by liuchuancong** [comment]
我没有14 的设备，明天找个模拟器试下
