### ISSUE TITLE
小case

### ISSUE THREAD

**Issue by hahuo** [liuchuancong/pure_live#71]
1在直播间直接操作弹幕设置的弹幕合并不起作用，然后到设置里的弹幕设置更改才起作用。
2更改相似度百分之百的弹幕之后弹幕一条都没了。相似度调成0，反而出现了更多的弹幕。这个逻辑是不是颠倒了？
3增加对已导入的m3u直播源可以编辑，或删除。如图所示，在分区→网络里，开始不会玩，误导入了多个直播源想删除只留一个，找不到地方。
4对直播源的某个频道收藏后，在关注里没有名称，都一个样，不易分辨。希望可以像分区那样有m3u名称和频道名称
5把频道的图标能以缩略图显示，替换现在的空白
如图所示

https://github.com/liuchuancong/pure_live/assets/125648416/86d109c0-74b0-4e83-9b9a-7b4db6affb62

**Comment by hahuo** [comment]
![Screenshot_20231204_075417](https://github.com/liuchuancong/pure_live/assets/125648416/586460d0-88cf-4f61-9be4-be0c90baaa8b)

**Comment by liuchuancong** [comment]
清除缓存重新添加，关注的还在无需担心。

**Comment by liuchuancong** [comment]
1.5.0修复标题显示
