### ISSUE TITLE
怎么用啊

### ISSUE THREAD

**Issue by yuf19-2022** [liuchuancong/pure_live#75]
叫在局域网下使用？，好不容易登录了，下载用户配置又不开放，这啥意思啊

**Comment by liuchuancong** [comment]
看更新提示，目前没在开发，没时间看

**Comment by liuchuancong** [comment]
数据远程同步不开发使用，数据库被恶意请求已经更换库了。

局域网使用是添加了本地webserver 服务，关闭即可
