### ISSUE TITLE
希望修复低版本安卓4.4.2 TV端、电视盒子端

### ISSUE THREAD

**Issue by wwb521** [liuchuancong/pure_live#78]
TV端、电视盒子端安装低配版本的存粹直播，显示解析包失败，希望可以修复这个问题，再次感谢，软件很方便、好用

**Comment by liuchuancong** [comment]
软件目前采用第三方依赖，例如，视频播放器，数据库，以及请求，暂不支持兼容低版本。目前最低是Android 21 即5.0
