### ISSUE TITLE
登录界面，遥控器不能选择账号输入框

### ISSUE THREAD

**Issue by li5bo5** [liuchuancong/pure_live#79]
登录、注册，都一样，不能用遥控器控制输入账号、密码
另外，设置里面的弹幕设置，也不能用遥控器上下选择，到第二个弹幕合并的时候，按上下键，就会左右移动滑块，无法跳转到下一个设置项。

**Comment by liuchuancong** [comment]
为何要登陆，使用本地服务同步

**Comment by liuchuancong** [comment]
登陆不开放，登上去你也无法拉取数据
