### ISSUE TITLE
可以让Windows端的应用多开吗？

### ISSUE THREAD

**Issue by RCwuhui** [liuchuancong/pure_live#8]
我不知道该怎么描述。
在您没接手前，Windows端在开启一个窗口时，可以再打开另外多个**独立的**窗口，这样就能同时观看多个直播

**Comment by liuchuancong** [comment]
不可以，已经为一个实例，多个实例会导致后面的打开都i是白屏

**Comment by M1NGc** [comment]
其实原版可以多开  而且声音大小也是独立  现在声音好像是接管了系统音量
