### ISSUE TITLE
后台播放应用被杀

### ISSUE THREAD

**Issue by Chokppl** [liuchuancong/pure_live#81]
Flyme11 A13 
后台播放会导致被APP被杀，电池优化已设定无限制。

**Comment by liuchuancong** [comment]
画中画呢

**Comment by Chokppl** [comment]
> 画中画呢

画中画和系统自带小窗什么的都不会被杀，这两个方式视频应该还是在前台的吧？另外我还发现一进入后台状态软件就会进入缓存了，有没有可能是这个原因系统判定不了这个是视频应用了？前台的时候是存在进程的。

**Comment by liuchuancong** [comment]
不会，这个是标准的后台服务

**Comment by Chokppl** [comment]
> 不会，这个是标准的后台服务

可否添加一个后台后的通知信息来进行保活呢？这样后台后也可以通过通知信息在任意界面下滑状态栏回到前台直播应用。如图所示
![S31217-22224384_com android systemui](https://github.com/liuchuancong/pure_live/assets/142749179/bfa908de-a4d8-422d-b0e4-45a619c53d89)
![S31217-22225874_com android settings](https://github.com/liuchuancong/pure_live/assets/142749179/bbda99e7-ff10-4004-8ac8-65588d4c9a7a)

**Comment by liuchuancong** [comment]
可以，我试试

**Comment by Chokppl** [comment]
> 可以，我试试

谢谢采纳。挺奇怪的一点是只有后台播放会被杀进程，只打开APP不在播放界面挂后台一晚都没事……

**Comment by liuchuancong** [comment]
已添加

**Comment by Chokppl** [comment]
> 已添加

最新版本吗？还是没有耶……甚至通知权限都授予不了，后台播放一会儿还是会被杀掉。
![S40110-22051923_com android settings](https://github.com/liuchuancong/pure_live/assets/142749179/9a903376-ca04-4310-85c9-d99d6000ed0b)
