### ISSUE TITLE
抖音平台存在直播获取失败的现象

### ISSUE THREAD

**Issue by twodoging** [liuchuancong/pure_live#86]
用抖音APP可以看到开播了，但纯粹直播关注页却显示未开播。启用搜索功能，可以搜到，但无法播放。不知是否和主播使用的直播软件有关。

**Comment by hbt2008** [comment]
抖音的直播打不开了，主播上线也不提示了，今天才出现的现象，应该是抖音屏蔽了

**Comment by liuchuancong** [comment]
抖音采用了新的构建方式即不对外开放接口，目前待研究
