### ISSUE TITLE
1.5.2版本平板界面异常

### ISSUE THREAD

**Issue by modj254** [liuchuancong/pure_live#89]
1.5.2版本平板界面异常，播放页非全屏下不显示右侧弹幕区域，无法切换清晰度，希望大佬修复。

**Comment by liuchuancong** [comment]
横屏切换比较好，因为平板一般默认全屏

**Comment by modj254** [comment]
![IMG_20240107_111239](https://github.com/liuchuancong/pure_live/assets/63177372/83af51b0-eb30-4b52-8829-54dc503ad16e)
![Screenshot_2024-01-07-11-10-14-128_com mystyle purelive](https://github.com/liuchuancong/pure_live/assets/63177372/d081f1df-90f7-4e7b-b295-82520ce3cf76)
最新1.5.3版本是默认全屏，但是按退出全屏按钮也还是全屏，也无法自动切换到竖屏。更喜欢1.5.0版本的布局，默认左边画面右边弹幕，然后手动全屏
