### ISSUE TITLE
投影仪 tv版 1.2.2 播放开始卡顿

### ISSUE THREAD

**Issue by hpkaiq** [liuchuancong/pure_live#9]
如题，极米投影仪，更新了1.2.2版本后播放开始卡顿，使用1.2.0没有问题，如果是更换了安卓播放器的原因，能不能设置添加个选择播放器选择的按钮，或者选择硬解解码还是软件解码

**Comment by liuchuancong** [comment]
新播放器bug较多，已经还原为exo-player
