### ISSUE TITLE
有的虎牙直播间没声音

### ISSUE THREAD

**Issue by Jacobax** [liuchuancong/pure_live#90]
主播：四次元先生
播的是电视剧《父母爱情》
同时间在另一款直播软件（dart_simple_live）上确认过是有声音的

版本：1.5.2
系统：MIUI14

**Comment by liuchuancong** [comment]
和直播源的拉流有关系，或者是播放器的问题，切换播放器或者尝试重启。代码是一样的 dart_simple_live

**Comment by Jacobax** [comment]
切换IjkPlayer就正常有声音了
原本看到说明只有ExoPlayer才能后台播放，不想换，但我试了IjkPlayer也可以后台播放
