### ISSUE TITLE
exo播放器打开后台播放后崩溃闪退（附带崩溃日志）

### ISSUE THREAD

**Issue by Chokppl** [liuchuancong/pure_live#92]
[crash-com-mystyle-purelive-12_01-21-42-12_688.zip](https://github.com/liuchuancong/pure_live/files/13919764/crash-com-mystyle-purelive-12_01-21-42-12_688.zip)
[crash-com-mystyle-purelive-12_01-21-42-16_495.zip](https://github.com/liuchuancong/pure_live/files/13919769/crash-com-mystyle-purelive-12_01-21-42-16_495.zip)
[crash-com-mystyle-purelive-12_01-21-42-17_575.zip](https://github.com/liuchuancong/pure_live/files/13919770/crash-com-mystyle-purelive-12_01-21-42-17_575.zip)
[crash-com-mystyle-purelive-12_01-21-43-39_362.zip](https://github.com/liuchuancong/pure_live/files/13919771/crash-com-mystyle-purelive-12_01-21-43-39_362.zip)

**Comment by liuchuancong** [comment]
可能是混淆导致的，感谢测试

**Comment by Chokppl** [comment]
> 可能是混淆导致的，感谢测试

举手之劳，希望有帮助。

**Comment by liuchuancong** [comment]
升级了exoplayer 和 删除了混淆 ，可以再试试

**Comment by Chokppl** [comment]
> 升级了exoplayer 和 删除了混淆 ，可以再试试

更新后依然出现闪退，附带日志

[crash-com-mystyle-purelive-31_01-20-45-37_014.zip](https://github.com/liuchuancong/pure_live/files/14111826/crash-com-mystyle-purelive-31_01-20-45-37_014.zip)

[crash-com-mystyle-purelive-31_01-20-45-38_279.zip](https://github.com/liuchuancong/pure_live/files/14111827/crash-com-mystyle-purelive-31_01-20-45-38_279.zip)

[crash-com-mystyle-purelive-31_01-20-45-50_943.zip](https://github.com/liuchuancong/pure_live/files/14111829/crash-com-mystyle-purelive-31_01-20-45-50_943.zip)

**Comment by liuchuancong** [comment]
@Chokppl  
```
1706705150.917  1000  5390  5414 D AlphaMe : getAllUnboundedPackages length=16
1706705150.919  1000  5700 24432 D Utils   : getAllUnboundedPackages(2) return [com.tencent.wework, com.baidu.BaiduMap, com.miHoYo.hkrpg, com.tencent.map, com.autonavi.minimap, com.miHoYo.Yuanshen, com.tencent.lolm, com.tencent.tmgp.sgame, com.shenyaocn.android.usbcamera, com.langge.map, com.cjapp.usbcamerapro, com.tencent.wemeet.app, com.android.browser, cn.wps.moffice_eng, com.gamestar.perfectpiano, com.tencent.tmgp.pubgmhd]
1706705150.934  1000  1689  4301 W ActivityManager: Unable to start service Intent { cmp=com.mystyle.purelive/c8.a } U=0: not found
```
应该是服务被限制了 白名单没有我这个App，所以不允许创建后台服务

**Comment by Chokppl** [comment]
> @Chokppl
> 
> ```
> 1706705150.917  1000  5390  5414 D AlphaMe : getAllUnboundedPackages length=16
> 1706705150.919  1000  5700 24432 D Utils   : getAllUnboundedPackages(2) return [com.tencent.wework, com.baidu.BaiduMap, com.miHoYo.hkrpg, com.tencent.map, com.autonavi.minimap, com.miHoYo.Yuanshen, com.tencent.lolm, com.tencent.tmgp.sgame, com.shenyaocn.android.usbcamera, com.langge.map, com.cjapp.usbcamerapro, com.tencent.wemeet.app, com.android.browser, cn.wps.moffice_eng, com.gamestar.perfectpiano, com.tencent.tmgp.pubgmhd]
> 1706705150.934  1000  1689  4301 W ActivityManager: Unable to start service Intent { cmp=com.mystyle.purelive/c8.a } U=0: not found
> ```
> 
> 应该是服务被限制了 白名单没有我这个App，所以不允许创建后台服务

后台播放是会被杀掉，可是打开应用不在播放页挂一天也没事……

**Comment by liuchuancong** [comment]
> > @Chokppl
> > ```
> > 1706705150.917  1000  5390  5414 D AlphaMe : getAllUnboundedPackages length=16
> > 1706705150.919  1000  5700 24432 D Utils   : getAllUnboundedPackages(2) return [com.tencent.wework, com.baidu.BaiduMap, com.miHoYo.hkrpg, com.tencent.map, com.autonavi.minimap, com.miHoYo.Yuanshen, com.tencent.lolm, com.tencent.tmgp.sgame, com.shenyaocn.android.usbcamera, com.langge.map, com.cjapp.usbcamerapro, com.tencent.wemeet.app, com.android.browser, cn.wps.moffice_eng, com.gamestar.perfectpiano, com.tencent.tmgp.pubgmhd]
> > 1706705150.934  1000  1689  4301 W ActivityManager: Unable to start service Intent { cmp=com.mystyle.purelive/c8.a } U=0: not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 应该是服务被限制了 白名单没有我这个App，所以不允许创建后台服务
> 
> 后台播放是会被杀掉，可是打开应用不在播放页挂一天也没事……

设置后台播放后，在播放页面会开启一个服务 就是android的service ，该服务会允许手机应用在后台运行，就是跳别的应用，会不进行打断播放。

**Comment by Chokppl** [comment]
> > > @Chokppl
> > > ```
> > > 1706705150.917  1000  5390  5414 D AlphaMe : getAllUnboundedPackages length=16
> > > 1706705150.919  1000  5700 24432 D Utils   : getAllUnboundedPackages(2) return [com.tencent.wework, com.baidu.BaiduMap, com.miHoYo.hkrpg, com.tencent.map, com.autonavi.minimap, com.miHoYo.Yuanshen, com.tencent.lolm, com.tencent.tmgp.sgame, com.shenyaocn.android.usbcamera, com.langge.map, com.cjapp.usbcamerapro, com.tencent.wemeet.app, com.android.browser, cn.wps.moffice_eng, com.gamestar.perfectpiano, com.tencent.tmgp.pubgmhd]
> > > 1706705150.934  1000  1689  4301 W ActivityManager: Unable to start service Intent { cmp=com.mystyle.purelive/c8.a } U=0: not found
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 应该是服务被限制了 白名单没有我这个App，所以不允许创建后台服务
> > 
> > 
> > 后台播放是会被杀掉，可是打开应用不在播放页挂一天也没事……
> 
> 设置后台播放后，在播放页面会开启一个服务 就是android的service ，该服务会允许手机应用在后台运行，就是跳别的应用，会不进行打断播放。

我看别的聚合类直播APP是会在进入后台后多出一个额外的进程的并且不会进入缓存，不晓得纯粹直播为什么一进行后台播放这个应用就全部就进入缓存了……然后一段时间后就突然无声音并被杀掉了。

![S40205-09170340_com android settings](https://github.com/liuchuancong/pure_live/assets/142749179/c5814dd0-06b3-4a16-aef9-fd1566168b8c)


![S40205-09180877_com android settings](https://github.com/liuchuancong/pure_live/assets/142749179/331c4445-af08-4443-8dd5-d5be1782735d)

**Comment by Chokppl** [comment]
> > > > @Chokppl
> > > > ```
> > > > 1706705150.917  1000  5390  5414 D AlphaMe : getAllUnboundedPackages length=16
> > > > 1706705150.919  1000  5700 24432 D Utils   : getAllUnboundedPackages(2) return [com.tencent.wework, com.baidu.BaiduMap, com.miHoYo.hkrpg, com.tencent.map, com.autonavi.minimap, com.miHoYo.Yuanshen, com.tencent.lolm, com.tencent.tmgp.sgame, com.shenyaocn.android.usbcamera, com.langge.map, com.cjapp.usbcamerapro, com.tencent.wemeet.app, com.android.browser, cn.wps.moffice_eng, com.gamestar.perfectpiano, com.tencent.tmgp.pubgmhd]
> > > > 1706705150.934  1000  1689  4301 W ActivityManager: Unable to start service Intent { cmp=com.mystyle.purelive/c8.a } U=0: not found
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 应该是服务被限制了 白名单没有我这个App，所以不允许创建后台服务
> > > 
> > > 
> > > 后台播放是会被杀掉，可是打开应用不在播放页挂一天也没事……
> > 
> > 
> > 设置后台播放后，在播放页面会开启一个服务 就是android的service ，该服务会允许手机应用在后台运行，就是跳别的应用，会不进行打断播放。
> 
> 我看别的聚合类直播APP是会在进入后台后多出一个额外的进程的并且不会进入缓存，不晓得纯粹直播为什么一进行后台播放这个应用就全部就进入缓存了……然后一段时间后就突然无声音并被杀掉了。
> 
> ![S40205-09170340_com android settings](https://private-user-images.githubusercontent.com/142749179/302149632-c5814dd0-06b3-4a16-aef9-fd1566168b8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTY0MjgsIm5iZiI6MTcwNzA5NjEyOCwicGF0aCI6Ii8xNDI3NDkxNzkvMzAyMTQ5NjMyLWM1ODE0ZGQwLTA2YjMtNGExNi1hZWY5LWZkMTU2NjE2OGI4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwMTIyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGZlZWRjNTJiMTkyOTk3MWMwNzgxY2M5MjU3MTkxN2M4ODY4OTAxNjFmZTFkYmQ0MGNmMjkyYjkyMjc3OGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H7C-lWCKX626G1lYAM3NFqPqE_tQs3gH2nYf0EV_5JU)
> 
> ![S40205-09180877_com android settings](https://private-user-images.githubusercontent.com/142749179/302149664-331c4445-af08-4443-8dd5-d5be1782735d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTY0MjgsIm5iZiI6MTcwNzA5NjEyOCwicGF0aCI6Ii8xNDI3NDkxNzkvMzAyMTQ5NjY0LTMzMWM0NDQ1LWFmMDgtNDQ0My04ZGQ1LWQ1YmUxNzgyNzM1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwMTIyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmQ3YzIyYmQzYTdiY2M5Yjc1N2Q4NzA3Y2EwNmRhYmQyYjVhNWRlOTZkYjc5ZGQ0ZjgxZjFlNmM1Y2E5NzA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CWNMyWSW4bmQ_4EMmR48z8OS1RbfBjCk8L-Vqt6Jo6c)

[https://github.com/guyijie1211/JustLive-Android](url) 这是截图应用的仓库，希望有帮助。

**Comment by Chokppl** [comment]
> > > > @Chokppl
> > > > ```
> > > > 1706705150.917  1000  5390  5414 D AlphaMe : getAllUnboundedPackages length=16
> > > > 1706705150.919  1000  5700 24432 D Utils   : getAllUnboundedPackages(2) return [com.tencent.wework, com.baidu.BaiduMap, com.miHoYo.hkrpg, com.tencent.map, com.autonavi.minimap, com.miHoYo.Yuanshen, com.tencent.lolm, com.tencent.tmgp.sgame, com.shenyaocn.android.usbcamera, com.langge.map, com.cjapp.usbcamerapro, com.tencent.wemeet.app, com.android.browser, cn.wps.moffice_eng, com.gamestar.perfectpiano, com.tencent.tmgp.pubgmhd]
> > > > 1706705150.934  1000  1689  4301 W ActivityManager: Unable to start service Intent { cmp=com.mystyle.purelive/c8.a } U=0: not found
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 应该是服务被限制了 白名单没有我这个App，所以不允许创建后台服务
> > > 
> > > 
> > > 后台播放是会被杀掉，可是打开应用不在播放页挂一天也没事……
> > 
> > 
> > 设置后台播放后，在播放页面会开启一个服务 就是android的service ，该服务会允许手机应用在后台运行，就是跳别的应用，会不进行打断播放。
> 
> 我看别的聚合类直播APP是会在进入后台后多出一个额外的进程的并且不会进入缓存，不晓得纯粹直播为什么一进行后台播放这个应用就全部就进入缓存了……然后一段时间后就突然无声音并被杀掉了。
> 
> ![S40205-09170340_com android settings](https://private-user-images.githubusercontent.com/142749179/302149632-c5814dd0-06b3-4a16-aef9-fd1566168b8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTY0MjgsIm5iZiI6MTcwNzA5NjEyOCwicGF0aCI6Ii8xNDI3NDkxNzkvMzAyMTQ5NjMyLWM1ODE0ZGQwLTA2YjMtNGExNi1hZWY5LWZkMTU2NjE2OGI4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwMTIyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGZlZWRjNTJiMTkyOTk3MWMwNzgxY2M5MjU3MTkxN2M4ODY4OTAxNjFmZTFkYmQ0MGNmMjkyYjkyMjc3OGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H7C-lWCKX626G1lYAM3NFqPqE_tQs3gH2nYf0EV_5JU)
> 
> ![S40205-09180877_com android settings](https://private-user-images.githubusercontent.com/142749179/302149664-331c4445-af08-4443-8dd5-d5be1782735d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTY0MjgsIm5iZiI6MTcwNzA5NjEyOCwicGF0aCI6Ii8xNDI3NDkxNzkvMzAyMTQ5NjY0LTMzMWM0NDQ1LWFmMDgtNDQ0My04ZGQ1LWQ1YmUxNzgyNzM1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQwMTIyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmQ3YzIyYmQzYTdiY2M5Yjc1N2Q4NzA3Y2EwNmRhYmQyYjVhNWRlOTZkYjc5ZGQ0ZjgxZjFlNmM1Y2E5NzA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CWNMyWSW4bmQ_4EMmR48z8OS1RbfBjCk8L-Vqt6Jo6c)

https://github.com/guyijie1211/JustLive-Android 这是截图应用的仓库，希望有帮助。

**Comment by liuchuancong** [comment]
@Chokppl  你看看是不是有什么 
![image](https://github.com/liuchuancong/pure_live/assets/36957912/0ee11ee9-0ccb-4b12-96cb-d1a4030e9e0e)
这种类似的限制，或者是android 版本不兼容，service 就是普通的一个函数 [android/src/main/kotlin/com/alizda/better_player/PlaybackService.kt ](https://github.com/liuchuancong/better_player/blob/media3/android/src/main/kotlin/com/alizda/better_player/PlaybackService.kt) 来自于官方media3 exo播放器文档 https://developer.android.google.cn/media/media3/session/background-playback?hl=zh-cn

**Comment by Chokppl** [comment]
> @Chokppl 你看看是不是有什么 ![image](https://private-user-images.githubusercontent.com/36957912/302220265-0ee11ee9-0ccb-4b12-96cb-d1a4030e9e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzQ5NDYsIm5iZiI6MTcwNzEzNDY0NiwicGF0aCI6Ii8zNjk1NzkxMi8zMDIyMjAyNjUtMGVlMTFlZTktMGNjYi00YjEyLTk2Y2ItZDFhNDAzMGU5ZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEyMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMDVmZDNjMmQyZTRiMTM4NWY1ZjcwNGRkY2VjN2JjMjFjMjQwOWY5NzViM2FmZTZlOGI2NDMzZTg2NWNkMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._wnAActZ1XXkc-O_uMZC7pj12R3ArFAlOUoU1NnE0So) 这种类似的限制，或者是android 版本不兼容，service 就是普通的一个函数 [android/src/main/kotlin/com/alizda/better_player/PlaybackService.kt ](https://github.com/liuchuancong/better_player/blob/media3/android/src/main/kotlin/com/alizda/better_player/PlaybackService.kt) 来自于官方media3 exo播放器文档 https://developer.android.google.cn/media/media3/session/background-playback?hl=zh-cn

这个权限和自启动权限我都打开了的，现在是使用ExoPlayer只要打开后台播放后进入播放页面就会闪退，并且ExoPlayer后台播放后会有一个系统播放的通知，闪退后得把后台权限和自启动权限调回智能不然会一直打不开闪退。不打开后台播放可正常进入播放页面。（ExoPlayer闪退日志在下面）

[crash-com-mystyle-purelive-05_02-20-13-08_337.zip](https://github.com/liuchuancong/pure_live/files/14165502/crash-com-mystyle-purelive-05_02-20-13-08_337.zip)
[crash-com-mystyle-purelive-05_02-20-13-15_694.zip](https://github.com/liuchuancong/pure_live/files/14165505/crash-com-mystyle-purelive-05_02-20-13-15_694.zip)
[crash-com-mystyle-purelive-05_02-20-13-16_809.zip](https://github.com/liuchuancong/pure_live/files/14165506/crash-com-mystyle-purelive-05_02-20-13-16_809.zip)
[crash-com-mystyle-purelive-05_02-20-13-49_283.zip](https://github.com/liuchuancong/pure_live/files/14165510/crash-com-mystyle-purelive-05_02-20-13-49_283.zip)
[crash-com-mystyle-purelive-05_02-20-14-04_431.zip](https://github.com/liuchuancong/pure_live/files/14165513/crash-com-mystyle-purelive-05_02-20-14-04_431.zip)
[crash-com-mystyle-purelive-05_02-20-14-13_770.zip](https://github.com/liuchuancong/pure_live/files/14165516/crash-com-mystyle-purelive-05_02-20-14-13_770.zip)

ljkPlayer解码可以后台播放，就是它会杀后台，上面的除了提供日志的都是在基于ljkPlayer解码截的图片。ExoPlayer解码只要打开后台播放选项就会闪退无法正常使用。

**Comment by Chokppl** [comment]
> > @Chokppl 你看看是不是有什么 ![image](https://private-user-images.githubusercontent.com/36957912/302220265-0ee11ee9-0ccb-4b12-96cb-d1a4030e9e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMzQ5NDYsIm5iZiI6MTcwNzEzNDY0NiwicGF0aCI6Ii8zNjk1NzkxMi8zMDIyMjAyNjUtMGVlMTFlZTktMGNjYi00YjEyLTk2Y2ItZDFhNDAzMGU5ZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEyMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMDVmZDNjMmQyZTRiMTM4NWY1ZjcwNGRkY2VjN2JjMjFjMjQwOWY5NzViM2FmZTZlOGI2NDMzZTg2NWNkMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._wnAActZ1XXkc-O_uMZC7pj12R3ArFAlOUoU1NnE0So) 这种类似的限制，或者是android 版本不兼容，service 就是普通的一个函数 [android/src/main/kotlin/com/alizda/better_player/PlaybackService.kt ](https://github.com/liuchuancong/better_player/blob/media3/android/src/main/kotlin/com/alizda/better_player/PlaybackService.kt) 来自于官方media3 exo播放器文档 https://developer.android.google.cn/media/media3/session/background-playback?hl=zh-cn
> 
> 这个权限和自启动权限我都打开了的，现在是使用ExoPlayer只要打开后台播放后进入播放页面就会闪退，并且ExoPlayer后台播放后会有一个系统播放的通知，闪退后得把后台权限和自启动权限调回智能不然会一直打不开闪退。不打开后台播放可正常进入播放页面。（ExoPlayer闪退日志在下面）
> 
> [crash-com-mystyle-purelive-05_02-20-13-08_337.zip](https://github.com/liuchuancong/pure_live/files/14165502/crash-com-mystyle-purelive-05_02-20-13-08_337.zip) [crash-com-mystyle-purelive-05_02-20-13-15_694.zip](https://github.com/liuchuancong/pure_live/files/14165505/crash-com-mystyle-purelive-05_02-20-13-15_694.zip) [crash-com-mystyle-purelive-05_02-20-13-16_809.zip](https://github.com/liuchuancong/pure_live/files/14165506/crash-com-mystyle-purelive-05_02-20-13-16_809.zip) [crash-com-mystyle-purelive-05_02-20-13-49_283.zip](https://github.com/liuchuancong/pure_live/files/14165510/crash-com-mystyle-purelive-05_02-20-13-49_283.zip) [crash-com-mystyle-purelive-05_02-20-14-04_431.zip](https://github.com/liuchuancong/pure_live/files/14165513/crash-com-mystyle-purelive-05_02-20-14-04_431.zip) [crash-com-mystyle-purelive-05_02-20-14-13_770.zip](https://github.com/liuchuancong/pure_live/files/14165516/crash-com-mystyle-purelive-05_02-20-14-13_770.zip)
> 
> ljkPlayer解码可以后台播放，就是它会杀后台，上面的除了提供日志的都是在基于ljkPlayer解码截的图片。ExoPlayer解码只要打开后台播放选项就会闪退无法正常使用。

只有ExoPlayer解码后台后会出现这个播放控件，奈何会闪退……
![S40205-20134256_com android systemui](https://github.com/liuchuancong/pure_live/assets/142749179/cfd2592f-c891-45df-a2c9-176d0336153b)

**Comment by liuchuancong** [comment]
@Chokppl 目前Exoplayer是自己维护的，所有的开发功能来自于谷歌的Media3 Api, 其他的播放器是第三方插件,服务在小米手机运行正常 ，如果无法使用就只能在设置中后台播放关闭了
