### ISSUE TITLE
B站个别直播间打不开

### ISSUE THREAD

**Issue by M1NGc** [liuchuancong/pure_live#93]

**Comment by M1NGc** [comment]
![image](https://github.com/liuchuancong/pure_live/assets/26264126/aa4e667a-1278-4ace-941f-ec6ed3cd43ee)

**Comment by liuchuancong** [comment]
尝试打开官方APP试一下看能看不，一般刷新就能解决

**Comment by liuchuancong** [comment]
B站手机直播无法观看
