### ISSUE TITLE
请问能否适配横屏模式？

### ISSUE THREAD

**Issue by q1351022** [liuchuancong/pure_live#94]
如题小米平板用了这个版本后，打开直播间只显示直播页面，不显示评论直接挡住了评论区没做横屏适配。原作者是有横屏适配的，搞得我回退版本了。

**Comment by liuchuancong** [comment]
竖屏看就好了

**Comment by q1351022** [comment]
我十几英寸的屏幕半斤重，你让我怎么拿的起来？哥！

**Comment by liuchuancong** [comment]
我也是小米平板，6 pro 打开自动旋转  没有任何问题 而且 软件也增加了旋转按钮 已经可以适配很多设备了

**Comment by q1351022** [comment]
平板横屏模式适配？.mp4
https://www.alipan.com/s/HVrHqhBuRei
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。

**Comment by q1351022** [comment]
没有适配呀，哥，上传文件太小了。发网盘了。

**Comment by q1351022** [comment]
用的最新版1.5.6。

**Comment by liuchuancong** [comment]
@q1351022 看到了 我在研究下

**Comment by liuchuancong** [comment]
@q1351022 我现在就是手机打开方向锁定  平板自动全屏

**Comment by liuchuancong** [comment]
1.6.0
