### ISSUE TITLE
刷新已开播刷新失败

### ISSUE THREAD

**Issue by Time34** [liuchuancong/pure_live#98]
![Screenshot_2024-02-03-19-23-31-921_com mystyle purelive](https://github.com/liuchuancong/pure_live/assets/128461914/f6b706bb-5484-4532-a298-28c2830663d5)

**Comment by liuchuancong** [comment]
不碍事 这个不会阻断其他直播间刷新 有的直播间被封了或者是直播间无法获取详情 就会出现此情况 @Time34
